### ISSUE TITLE
ext_tables.sql -> Customfield 0-9 definition should be removed

### ISSUE THREAD

**Issue by velletti** [evoWeb/sf_register#10]
as the sql Definition of costom0 to custom9 Fields  with varchar(1) is shorter than the TCA definitions in 
https://github.com/evoWeb/ew_sfregister_extended 
the stored data is always just one char. 

BTW: The documentation should be updated and include a link to 
https://github.com/evoWeb/ew_sfregister_extended (i created also 3 Issues there with solutions)
and 
https://typo3.org/extensions/repository/view/extender

**Comment by garbast** [comment]
Link added in documentation of extending.
