### ISSUE TITLE
Required argument "user" is not set for Evoweb\SfRegister\Controller\FeuserEditController->preview.

### ISSUE THREAD

**Issue by florida192** [evoWeb/sf_register#101]
Hello, 

I got this message when I tried to change language in the confirmation page. 

#1298012500 TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException
Required argument "user" is not set for Evoweb\SfRegister\Controller\FeuserEditController->preview.

Thanks

**Comment by garbast** [comment]
This could only happen if you access the preview step without submitting the form. So technically this is impossible if you use the form as entry point.

**Comment by yogurtcu** [comment]
I have the same error, I am already logged in, change my personal data, click on save and get to the preview page. There I decide to change the language to English instead of clicking on save, same error message.

@garbast: Perhaps my detailed description will help you to better understand the issue...

**Comment by garbast** [comment]
The registration does not allow changing the language in the preview. So clearly you did not used the back button but any other link on the website. in that case you did not transfer the data in the hidden fields but lost all information. This expecation is not covered by the registration.

**Comment by erguenyogurtcu** [comment]
If it is not allowed, it must either be prevented or caught. I understand the problem with the missing parameter of the user data, but it's not user-friendly. Wouldn't it make more sense to catch this in "previewAction" and at least redirect the visitor from the preview back to the form...? I always think, a TYPO3 error message is taboo.

**Comment by garbast** [comment]
Can you show me in your website where error is?
