### ISSUE TITLE
Ajax call (country-zone selection) not working on subpages (TYPO3 9)

### ISSUE THREAD

**Issue by mat-hew1** [evoWeb/sf_register#103]
TYPO3 9.5 (maybe earlier versions too with RealUrl / CoolUri)
On subpages with speaking path segments "/subpage" ends ajax call with 404, because of called URI: "/subpage/index.php?ajax=sf_register" (Resources/Public/JavaScript/sf_register.js:306).
We don't want to rewrite each URI which ends with index.php...

**Comment by garbast** [comment]
This normals happens when you have no baseURL or you are using some stupid browser that do not respect the baseURL for javascript. No solution here. You need to modify a local instance of the file on your own.

**Comment by mat-hew1** [comment]
I not pretty, but you're right. I forgot the baseURL. I apologize for spam.
