### ISSUE TITLE
Translations and/or override mechanism missing

### ISSUE THREAD

**Issue by mat-hew1** [evoWeb/sf_register#104]
Some translations into German are available, some are missing. It's pretty inconsistent.
A mechanism for extensibility of translations would be very helpful here, e.g. via TypoScript settings. However, currently all translations are bound to the extension name, so we have to overwrite all needed places (Fluid Templates, Mail Service/getSubject, etc.)

**Comment by garbast** [comment]
Feel free to propose a PR with changes to the locallang.xlf.

**Comment by mat-hew1** [comment]
I think an override mechanism would be better. I will prepare a PR as a proposal in a few weeks, at the moment I do not have enough time for.

**Comment by garbast** [comment]
Do you know, that you can override translations via TypoScript

plugin.tx_sfregister._LOCAL_LANG.default.title_none = No title
plugin.tx_sfregister._LOCAL_LANG.de.title_none = Kein Titel

These are available for all translations running in frontend mode.
