### ISSUE TITLE
User disabled after register and before confirm

### ISSUE THREAD

**Issue by mat-hew1** [evoWeb/sf_register#105]
Setting "disabled" for user after save is (under certain conditions) hardcoded, but not always useful. They are two different configurations for groups before and after confirmation. It doesn't make sense to disable user, if admin activation is not needed. Example: group 1 - users who didn't confirm they e-mail yet (some information contents will be displayed for these users - e.g. link to resend confirmation mail), group 2 - registered users.

**Comment by garbast** [comment]
The behaviour is by intend and will not change. You need to disable them for double optin for example.

**Comment by mat-hew1** [comment]
How?
```
    public function saveAction(\Evoweb\SfRegister\Domain\Model\FrontendUser $user)
    {
        if ($this->settings['confirmEmailPostCreate'] || $this->settings['acceptEmailPostCreate']) {
            $user->setDisable(true);
            $user = $this->changeUsergroup($user, (int) $this->settings['usergroupPostSave']);
```

**Comment by garbast** [comment]
confirmEmailPostCreate stands for the double optin and you should use it for that purpose

**Comment by mat-hew1** [comment]
Okay, I solved it my own way, with the signals. IMHO, with 2 different groups, it is also double opt-in, you don't have to always disable the user, could be configurable... It's a matter of opinion.
