### ISSUE TITLE
sf_register.min.css is missing in TER Version 10.0

### ISSUE THREAD

**Issue by web2date** [evoWeb/sf_register#107]
After install of sf_register 10.0 in TYPO3 10.4.1 a warning appears in Debug Mode
PHP Warning: file_get_contents(/home/www/xxxxxx/html/typo3/typo3conf/ext/sf_register/Resources/Public/Stylesheets/sf_register.min.css)
The file is missing in sf_register/Resources/Public/Stylesheets/ in TER Version

**Comment by garbast** [comment]
Fixed with a9efa23d779a027df136745bd8eb30ddf7875e1e
