### ISSUE TITLE
domain in email-links missing 

### ISSUE THREAD

**Issue by wini2** [evoWeb/sf_register#109]
hello,
before i start moaning ;-)  great extension. thanks a lot.

i use your ext. the first time (so forgive me, if i overlooked the setting). the links in the emails send by the extension point to the right page, but without the domain.

e.g. 
/login/mich-registieren?tx_sfregister_create%5Baction%5D=confirm&tx_sfregister_create%5Bcontroller%5D=FeuserCreate&tx_sfregister_create%5Bhash%5D=2844df41a19e79c92f11572a6b7a0c44ae1ca3bb&tx_sfregister_create%5Buser%5D=5&cHash=bdb48d4d4c32e05734ec4dc50a88fd5f

not 

https://mydomain.de/login/mich-registieren?tx_sfregister_create%5Baction%5D=confirm&tx_sfregister_create%5Bcontroller%5D=FeuserCreate&tx_sfregister_create%5Bhash%5D=2844df41a19e79c92f11572a6b7a0c44ae1ca3bb&tx_sfregister_create%5Buser%5D=5&cHash=bdb48d4d4c32e05734ec4dc50a88fd5f

config.baseURL doesn't help. 

my stupidity or missing hint in the manual?

TYPO3 10.4.3/sf_register 10.0.1

btw: maybe a missunderstanding, but the manual says 'in the page page properties on tab Resources select the storage folder in field ‘General Record Storage Page’. but there is no field. could it be, that the field in the ce is meant?

**Comment by garbast** [comment]
It should work

`<register:link.action arguments="{user: user.uid}" action="confirm" controller="FeuserCreate" absolute="true">
			<f:translate key="email_user_confirm_link"/>
		</register:link.action>`

But this this only delivers a link with domain if your site config has a valid baseVariant or base. If that part is not configured with a domain you will not get a absolute url. TypoScript baseUrls does not matter for that anymore.
