### ISSUE TITLE
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException

### ISSUE THREAD

**Issue by dextar1** [evoWeb/sf_register#110]
I am getting this error when i am using this ext with recaptcha on TYPO3 10 LTS

The "Evoweb\Recaptcha\Adapter\SfRegisterAdapter" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by garbast** [comment]
You need to install evoweb/recaptcha to get this working

**Comment by dextar1** [comment]
recaptcha is also installed

**Comment by MohsinQK** [comment]
@garbast I have also the same issue, Latest evoweb/recaptcha is installed but same issue.

**Comment by MohsinQK** [comment]
Something is wrong in Service Configuration.
https://github.com/evoWeb/sf_register/blob/develop/Configuration/Services.yaml

**Comment by garbast** [comment]
This issue has nothing to do with https://github.com/evoWeb/sf_register/blob/develop/Configuration/Services.yaml

The class Evoweb\Recaptcha\Adapter\SfRegisterAdapter is not part of EXT:sf_register but of EXT:recaptcha.

If at all the configuration is missing in https://github.com/evoWeb/recaptcha/blob/develop/Configuration/Services.yaml but there you find that the adapter is publicly available.

I cant reproduce the problem in my development installation. Without access to a system where i can debug the problem, i cant help you with that.

Either you can provide me with such an access or hand in a PR which fixes the problem.
