### ISSUE TITLE
Unique reacts as well if it's own entry

### ISSUE THREAD

**Issue by bucheggerOnline** [evoWeb/sf_register#111]
Hi.
I tried to make a form to change the username and the mail. But the UniqueValidator also reacts if it's the own mail or username. Maybe there should be a exception for that. Otherwise it's always necessary to make a page just to change the mailaddress and another one to change the username. if it's together with other fields and it shouldn't be changed at all it will always have an error.
Kind Regards,
Matthias

**Comment by garbast** [comment]
Feel free to submit a PullRequest for this feature.

**Comment by garbast** [comment]
Closed due to inactivity
