### ISSUE TITLE
Unable to Remove frontend user with given plugin

### ISSUE THREAD

**Issue by MohsinQK** [evoWeb/sf_register#113]
i got this error when try to remove one user by clicking on the link in email for confirmation to delete.

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1470230767: Unknown column '0' in 'field list' | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /var/www/clients/client77/web1020/web/current/typo3_src/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 203. Requested URL: https://mydomain.com/mein-profil.html?tx_sfregister_delete%%5Baction%%5D=confirm&tx_sfregister_delete%%5Bcontroller%%5D=FeuserDelete&tx_sfregister_delete%%5Bhash%%5D=19213e4696e057dff788b7772cdf98d3c0a1f3fe&tx_sfregister_delete%%5Buser%%5D=8865&cHash=4772336f866d4f1203a02e05634413fc`

in the function on Typo3DbBackend.php in line 203, which update the fe user is taking in the fields variable 

![image](https://user-images.githubusercontent.com/1622975/85022482-cbbe3700-b18c-11ea-8339-175785f2d219.png)

**Comment by garbast** [comment]
This is nothing the extension can fix. In the confirmAction of the DeleteController the extbase repository is used:
```
            $this->userRepository->remove($user);
            $this->persistAll();
```
The remove is taken care by the base \TYPO3\CMS\Extbase\Domain\Repository\FrontendUserRepository and more precise the \TYPO3\CMS\Extbase\Persistence\Repository.

persistAll triggers the \TYPO3\CMS\Extbase\Persistence\Generic\Backend::removeEntity and your error shows that $deletedColumnName is empty.

The only assumption i can give is, that the TCA is not correct in your installation whichs leads to a corrupt dataMap->getDeletedFlagColumnName.
