### ISSUE TITLE
Bug in ext_locanconf (9.4.0)

### ISSUE THREAD

**Issue by moskos88** [evoWeb/sf_register#121]
Hallo!
I just found out that in version 9.4.0 there is a bug in the ext_localconf.php file. In my environment, it causes a cache problem (change password action is always called twice).
There is a quick solution for it.
At line 32 please put the correct controller name for invite case. I was trying to fork the repo and propose my own pull request, but there is no branch for this purpose. Is there still a possibility to fix it?

**Comment by garbast** [comment]
by now, it wasn't necessary to have something fixed in 9. So i need to create a branch from the latest tag that was compatibile with 9. Please add you patch file here and i apply it.

**Comment by moskos88** [comment]
So the content of the file is here: https://github.com/moskos88/sf_register/blob/fixLocalConf/ext_localconf.php

Big thanks in advice!

**Comment by garbast** [comment]
New release 9.4.1 is on the way
