### ISSUE TITLE
Bug in FeuserEditController (10.0.1)

### ISSUE THREAD

**Issue by nebulousNick** [evoWeb/sf_register#122]
Hi,
I guess there's a bug in the FeuserEditController (10.0.1).
In line 52 (if ($userData['uid'] == $userId) {... } ) you try to use $userData as an array, but there is an Evoweb\SfRegister\Domain\Model\FrontendUser object. That hppens, if you want to get back from the overview of your changed data to the form.

Message is "Cannot use object of type Evoweb\SfRegister\Domain\Model\FrontendUser as array".

Quick BugFix: if ($userData->getUid() == $userId) {...} 

But this does not work in Validation context, where $userData seems to be an array?

Greetings,
Nick

**Comment by garbast** [comment]
I added an check if the userData is an array. Please check if this fixes your problem.

**Comment by nebulousNick** [comment]
Works.

**Comment by garbast** [comment]
Released with 10.0.2
