### ISSUE TITLE
Question: failing to extend with new fields

### ISSUE THREAD

**Issue by fsuter** [evoWeb/sf_register#124]
Hi Sebastian,

I am trying to use the "extender" feature to add new fields. In fact I had it working a lot time ago, with old versions of everything. Now I am updating this old web site to TYPO3 10, sf_register 10 and extender 7, and I can't make it fully work anymore. In fact I'm just failing at the last step.

What works:

- I can see the new fields in the Plugin configuration
- I can display the new fields in the Create or Edit form

What does not work:

- when I save the data after editing, I get an exception: "Exception while property mapping at property path "": Property "tx_inti_job" was not found in target object of type "Evoweb\SfRegister\Domain\Model\FrontendUser"."

Do you have any idea what could be wrong? Are the underscores an issue (although the property "txIntiJob" exists in the compiled/extended class)?

Please tell me if you need more information. It's a bit hard to put my code here, since there are actually so many files involved (PHP, TypoScript, SQL, etc.).

Thanks in advance for any hint.

**Comment by garbast** [comment]
Without having access to the system, i can only guess. The field must be names txIntiJob in the template, comparable to https://github.com/evoWeb/sf_register/blob/7cb241cd75526650a38dd484f619f072e5fa7151/Configuration/TypoScript/Fields/setup.typoscript#L33

**Comment by fsuter** [comment]
Yes, that was it!!! Thanks a lot for your quick reply and your support.

Sorry for the late followup, it's a side project on which I don't work every day.
