### ISSUE TITLE
Adding a field with MM relations

### ISSUE THREAD

**Issue by fsuter** [evoWeb/sf_register#125]
Hi,

I have extended the fe_users table with a field that has a MM relation to another table. I am displaying it in form and preview mode by using a dedicated partial. So far so good.

I had an exception when trying to preview or save, complaining that it could not convert a string (the uid of each element in the relation) to the corresponding object type (as declared in my extended fe_user model class). I could achieve what I wanted by creating a specific TypeConverter and Xclassing `\Evoweb\SfRegister\Controller\FeuserEditController` to add an `initializeAction` method where I could invoke my TypeConverter.

The side effect of this (and I don't know why exactly) is that the "user" parameter was already converted to a model object, which then caused an error in `\Evoweb\SfRegister\Controller\FeuserEditController` on line 52 where there is the following check: `if ($userData['uid'] == $userId) {`. I worked around it by overriding the `formAction` method.

So in the end everything works, but I feel like I used too many workarounds. Maybe I took a far too complicated path and I'm wondering if you have any experience or advice about this.

**Comment by garbast** [comment]
Sadly enough, all of this is realy necessary in extbase. Line 52 ich modified in develop branch to have an is_array check in case the model was already instantiated. I will release the change the upcoming weekend. You could require the dev branch for now and change next week back to a tag.

**Comment by fsuter** [comment]
Thanks for the confirmation and the quick reaction.
