### ISSUE TITLE
The account user@mail.com that you are trying to activate is already active.

### ISSUE THREAD

**Issue by ammodytes** [evoWeb/sf_register#126]
Hi,

I have problem with user activation via email link, there is this message: The account user@mail.com that you are trying to activate is already active.

What can be wrong? Here is my constants:

`plugin.tx_sfregister.settings.notifyAdmin.editSave = 0
plugin.tx_sfregister.settings.notifyAdmin.editConfirm = 0
plugin.tx_sfregister.settings.notifyAdmin.editAccept = 0
plugin.tx_sfregister.settings.notifyAdmin.inviteInvite = 0
plugin.tx_sfregister.settings.notifyAdmin.resendMail = 0
plugin.tx_sfregister.settings.notifyUser.createSave = 1
plugin.tx_sfregister.settings.notifyUser.createRefuse = 0
plugin.tx_sfregister.settings.notifyAdmin.deleteSave = 0
plugin.tx_sfregister.settings.notifyUser.createAccept = 1
plugin.tx_sfregister.settings.notifyUser.createDecline = 0
plugin.tx_sfregister.settings.notifyUser.editSave = 1
plugin.tx_sfregister.settings.notifyUser.editConfirm = 0
plugin.tx_sfregister.settings.notifyAdmin.deleteConfirm = 0
plugin.tx_sfregister.settings.notifyAdmin.createDecline = 0
plugin.tx_sfregister.settings.notifyUser.inviteInvite = 0
plugin.tx_sfregister.settings.acceptEmailPostCreate = 0
plugin.tx_sfregister.settings.acceptEmailPostEdit = 0
plugin.tx_sfregister.settings.confirmEmailPostEdit = 0
plugin.tx_sfregister.settings.acceptEmailPostConfirm = 0
plugin.tx_sfregister.settings.confirmEmailPostAccept = 0
plugin.tx_sfregister.settings.notifyAdmin.createAccept = 0
plugin.tx_sfregister.settings.notifyAdmin.createSave = 1
plugin.tx_sfregister.settings.notifyAdmin.createConfirm = 0
plugin.tx_sfregister.settings.notifyAdmin.createRefuse = 0
plugin.tx_sfregister.settings.notifyUser.editAccept = 0
plugin.tx_sfregister.settings.redirectPostRegistrationPageId = 424
plugin.tx_sfregister.settings.redirectPostActivationPageId = 20
plugin.tx_sfregister.settings.useEncryptedFilename = 0
plugin.tx_sfregister.settings.redirect.page = 20
plugin.tx_sfregister.persistence.storagePid = 343
plugin.tx_sfregister.settings.notifyUser.deleteSave = 0
plugin.tx_sfregister.settings.notifyUser.createConfirm = 0
plugin.tx_sfregister.settings.notifyUser.resendMail = 0
plugin.tx_sfregister.settings.notifyUser.deleteConfirm = 0
plugin.tx_sfregister.settings.confirmEmailPostCreate = 1`

Thanks :)

**Comment by garbast** [comment]
The account is already active as it is stated. Read the documentation, everything is explained in it.
