### ISSUE TITLE
Better eMail Validation

### ISSUE THREAD

**Issue by toco3** [evoWeb/sf_register#129]
Hello!
First of all: thank you for your work and this great extension!

I run into following issue: It is possible to enter e.g. ce@toco3 at email address.
As far as I could see, it is only validated if there is a '@' in the string.... 
This could break further processes, where you really need an correct email address format.

I wrote the following Validator:

`<?php
namespace Evoweb\SfRegister\Validation\Validator;

/***************************************************************
 * Copyright notice
 *
 * (c) 2011-2019 Sebastian Fischer <typo3@evoweb.de>
 * All rights reserved
 *
 * This script is part of the TYPO3 project. The TYPO3 project is
 * free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * The GNU General Public License can be found at
 * http://www.gnu.org/copyleft/gpl.html.
 *
 * This script is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/

/**
 * A empty validator this is used in validation of a new created user to ensure that the uid is empty
 */
class EmailValidator extends \TYPO3\CMS\Extbase\Validation\Validator\AbstractValidator
{

    /**
     * If the given value is empty
     *
     * @param string $value The value
     */
    public function isValid($value)
    {
        if (!filter_var($value, FILTER_VALIDATE_EMAIL)) {
            $this->addError(
                $this->translateErrorMessage('error_1221559976', 'SfRegister', [$value]),
                1221559976
            );
        }
    }
}`

And added it to the Validators:

`plugin.tx_sfregister.settings.validation.create.email.2  = "Evoweb.SfRegister:Email"`

Perhaps you would like to add this code to the extension. I think it is a good idea to use the standard PHP function to validate the email address?!

Thank you 

Christian

P.S.: 
TYPO3 10.4.6
sf_register 10.0.1

**Comment by garbast** [comment]
The default validation for email address is the extbase EmailAddress validator that uses GeneralUtility::validEmail which is totally fine and enough.

If you feel, that you need more validation, you are free to use a custom validator and register it in TypoScript. But i wont add your suggestion to the extension as it does not improve the default setup.
