### ISSUE TITLE
StaticCountryZoneRepository doesn't rely on database abstraction

### ISSUE THREAD

**Issue by InvisibleKind** [evoWeb/sf_register#13]
This is a copy-paste of removed issue form TYPO3 Forge.

For some reason `Evoweb\SfRegister\Domain\Repository\StaticCountryZoneRepository` makes such a call:

``` php
$query->statement('SELECT * FROM static_country_zones WHERE zn_country_iso_2 = ? AND deleted = 0', array($iso2));
```

While same can be achieved by:

``` php
$query->matching($query->equals('zn_country_iso_2', $iso2));
```

Also since TYPO3 7.2 there is a bug [#67375](https://forge.typo3.org/issues/67375), which is related to using placeholders in statement() call. So, it is another good reason to change that line.

**Comment by garbast** [comment]
Feel free to hand in a pull request

**Comment by InvisibleKind** [comment]
In fact it is already present in 'master' branch (probably, that's why issue was deleted from Forge), but not in 6.2.x branch, which should be anyway compatible with TYPO3 7.x
Cherry-picking of commit, mentioned in PR, was painful, because lot of things were changed there, so I just changed the line, which brings an error.

**Comment by AdvanceWM** [comment]
When I tried applying the bug fix, the form populated, but had no countries in the Country dropdown. TYPO3 7.6.11 and sf_register 6.2.9

**Comment by garbast** [comment]
Closed due to inactivity. The merge happend. If there is something else broken please open a new PR.
