### ISSUE TITLE
Email confirmation still not working

### ISSUE THREAD

**Issue by sendTas** [evoWeb/sf_register#130]
I took your setup, but no emails are sent. The system itself can send emails.

Example:
plugin.tx_sfregister.settings.confirmEmailPostCreate = 1
plugin.tx_sfregister.settings.notifyUserPostCreateSave = 1
plugin.tx_sfregister.settings.notifyUserPostCreateConfirm = 1
plugin.tx_sfregister.settings.usergroupPostSave = 2144
plugin.tx_sfregister.settings.usergroupPostConfirm = 2145

_Originally posted by @garbast in https://github.com/evoWeb/sf_register/issues/22#issuecomment-230994469_

**Comment by garbast** [comment]
The E-Mail Handling is working as expected and documented.

The issue tracker ist not for individual support. If you need help, i can offer you support for a fee of 80€ per hour.
