### ISSUE TITLE
nice form plugin 

### ISSUE THREAD

**Issue by Berlintypo3** [evoWeb/sf_register#132]
hi.. i testet the minimal plugin by step to step. 
where is the plugin for the frontend login? 
I use also the intern phpmailer but no mail coming in 
and in the backend i dont have anything for the registration user entry.  
so what happend?

**Comment by garbast** [comment]
The login is provided by the core so why does the registration extension need to provide it?

You need to configure the extension via typoscript to get mails send and define where the records get stored.

Beyond this answer i can provide you paid support to analyse your problems and configure your system. Invoice price is 80€ per hour counting every started quarter hour.
