### ISSUE TITLE
Older Members cannot register

### ISSUE THREAD

**Issue by web-commerce-og** [evoWeb/sf_register#133]
Members born before 1960 cannot register if the birthdate is required. Also inputing a date via dropdown is quite tiresome.

I would suggest switching the template to the browsers default <input type="date">

Maybe also add a JavaScript fallback for Internetexplorer. IE Edge can already handle type=date

**Comment by linawolf** [comment]
I just noted I used the wrong account to post the above issue. Sorry about that. It was me.

Greetings Lina

**Comment by garbast** [comment]
The best thing of fluid templates is the possibility to override them. The current templates in the extension are only suggestion and as such i wont change them. The date field in it self has to many UX problems, that i'm not willing to change towards them.
