### ISSUE TITLE
default form partials do not show backendLabel

### ISSUE THREAD

**Issue by web-commerce-og** [evoWeb/sf_register#134]
In many cases I would like to reuse default partials like Form/Textfield  or Form/Select for my own fields.

However if I do the backendLabel as described here: 
https://docs.typo3.org/p/evoweb/sf-register/9.4/en-us/Extendability/Index.html

will not be outputted. 

Therefore I do have to override each form Partial just to change the label from

<f:translate id="{fieldName}" />

into

<f:translate id="{fieldName}" default="{options.backendLabel}"/>

I would suggest adding the later version to the extensions templates as they don't have a downside when the backendLabel is not set. It would also enable overriding the default labels of excisting fields via TypoScript.

**Comment by linawolf** [comment]
I just noted I used the wrong account to post the above issue. Sorry about that. It was me.

Greetings Lina

**Comment by garbast** [comment]
To add lables you just need to add them to TypoScript _LOCAL_LANG of the extension. The backendLabels are not supposed to be used in the frontend but just for the selectbox in the plugin element. And in addition the backendLabels to not support the translation layer of TYPO3.
