### ISSUE TITLE
Duplicate User possible when using confirmEmailPostCreate

### ISSUE THREAD

**Issue by FlyKasual** [evoWeb/sf_register#135]
When setting `confirmEmailPostCreate = 1` to implement double-opt-in, the user is shown a message telling them to click the link in the confirmation email. Reloading this page creates the user again and resends the confirmation email. Some sort of check whether the user to be created already exists should be in place. Alternatively, it could be possible to use [PRG](https://en.wikipedia.org/wiki/Post/Redirect/Get) to get around the issue.

**Comment by garbast** [comment]
Sorry but if you need PRG, you could hand in a pull request. On the other hand, you could implement that concept with a small javascript in your template.

**Comment by FlyKasual** [comment]
I'm an idiot. `redirectPostRegistrationPageId` already pretty much implements PRG. Sorry for stealing your time.
