### ISSUE TITLE
You can create the same user twice

### ISSUE THREAD

**Issue by firmenpunkt** [evoWeb/sf_register#136]
I use the e-mailaddress as userneme and the system lets several users register with the same username and mailaddress . Typo3 10 
sf_register | 10.1.5

**Comment by garbast** [comment]
You need to add "Evoweb.SfRegister:Unique" to plugin.tx_sfregister.settings.validation.create.email.3 and "Evoweb.SfRegister:Unique", options={"global": 1} to plugin.tx_sfregister.settings.validation.create.email.4 to prevent same email addresses.
