### ISSUE TITLE
Password is not hashed when User changes the Password via Edit User Plugin

### ISSUE THREAD

**Issue by VaIcorn** [evoWeb/sf_register#138]
# Steps to Reproduce
1 Register a new User or Login to an existing one
2 Visit a Page with the Edit User Plugin
3 Change your Password
4 Logout
5 Login

# Expected
The User can Login and the Password is hashed.

# Actual
The User cannot Login. When checking the DB the Password is saved in plain Text.

**Comment by garbast** [comment]
To change passwords never use the edit plugin for that. There is a dedicated password change plugin for that.

**Comment by VaIcorn** [comment]
Ah ... I did not notice / expect that. That was my Mistake. Thank you very much for you fast Response 👍 

But it is a little misleading since the Edit User Plugin offers every plausible opption tocChange the Password: Old Password, Password, Password repeat.
