### ISSUE TITLE
DateSelect.html

### ISSUE THREAD

**Issue by Zillion01** [evoWeb/sf_register#140]
DateSelect.html form and preview partials have hardcoded properties for dateOfBirth, so it's unusable for extended fields when also dateOfBirth field is used. Both values will be the same at the preview page. 

Solution proposed: change in database to date instead of int, so no need for tricks to compose the date in the model.

**Comment by garbast** [comment]
Feel free to propose a PR

**Comment by Zillion01** [comment]
Thank you, I might in the future when I don't need to work on Saturday evening too ;)

**Comment by garbast** [comment]
It will be 100% a breaking change, that's why i want to see what you come up with and if it is worth the break.

**Comment by garbast** [comment]
Closed due to no action
