### ISSUE TITLE
srfreecaptcha

### ISSUE THREAD

**Issue by Zillion01** [evoWeb/sf_register#141]
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException
The "Evoweb\SfRegister\Services\Captcha\SrFreecapAdapter" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```
Frontend error when including the captcha as field, I guess the constructor not works anymore like this in 10.4.

TYPO3 10.4.11
sf_register 10.1.5
sr-freecap 2.6.1

**Comment by garbast** [comment]
Please try, if the dev branch is now working for you.

**Comment by Zillion01** [comment]
Sebastian you rock!
Hopefully next year again a beer at some T3 event.

Mfg
Jacco van der Post

**Comment by Zillion01** [comment]
If you gonna publish a new release maybe also change in the manual the ext_localconf.php part for adding custom properties.

`$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['sf_register']['extender'][\Evoweb\SfRegister\Domain\Model\FrontendUser::class]['cem_sitepackage'] =
        'EXT:cem_sitepackage/Classes/Domain/Model/FrontendUser.php';`

EXTENSIONS instead of EXTCONF now. Thanks.

**Comment by garbast** [comment]
You are right, the manual needs to be changed to the 10+ version. Thanks for the hint.

**Comment by averlon** [comment]
Hi,
I still have the same issue.
sf_register 10.1.6
typo3: 10.4.16
sr-freecap: 2.6.2

**Comment by jkujku** [comment]
This is solved in the dev branch (as mentioned above). 

If you don't use the dev branch you have to set the Adapter public in (your|any) Service.yaml

```
# Configuration/Services.yaml
services:
  Evoweb\SfRegister\Services\Captcha\SrFreecapAdapter:
    public: true
```

**Comment by garbast** [comment]
Fix is backported to dev-10.x
