### ISSUE TITLE
Exception after create confirmation

### ISSUE THREAD

**Issue by AstCommodore** [evoWeb/sf_register#143]
Hello there!

I've got an reproducible exception after creating an account and reloading the confirmation: 

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1217839467: Could not ultimately dispatch the request after 101 iterations. Most probably, a @TYPO3\CMS\Extbase\Annotation\IgnoreValidation annotation is missing on re-displaying a form with validation errors. | TYPO3\CMS\Extbase\Mvc\Exception\InfiniteLoopException thrown in file /html/typo3/typo3_src-10.4.12/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php in line 85. Requested URL: registrierung?tx_sfregister_create%%5Baction%%5D=preview&tx_sfregister_create%%5Bcontroller%%5D=FeuserCreate&cHash=80b0dddfd01ded2b8949c5f2fcf8ed3a`

TYPO3 10.4.12
extender 7.0.1
sf_register 10.1.5

Is this problem only avoidable by setting plugin.tx_sfregister.settings.redirectPostRegistrationPageId?

Greetings
André

**Comment by garbast** [comment]
Having a look at FeuserCreateController::previewAction you see, that redirectPostRegistrationPageId has no influence here. Dont know how you got in this situation, but it seems, that your setup does something normaly impossible in the previewAction.
