### ISSUE TITLE
language in frontend always english

### ISSUE THREAD

**Issue by averlon** [evoWeb/sf_register#146]
Hi,
I have a website with only one language. The default language is set to "Deutsch" (German).
The language field in the plugin "Registration: create" always shows English names.

static-info-tabeles installed and static-info-tables-de installed.

Could you give me a hint where to change something to get the values in de_DE.
Thanks
Regards
Karl-Heinz

**Comment by garbast** [comment]
Sorry, but this issue tracker is for problems with the extension, not problems with your installation. There is paid support on quarter hours, for problems like yours.
