### ISSUE TITLE
Accept fails with message 'user alread registered'

### ISSUE THREAD

**Issue by g-nebel** [evoWeb/sf_register#147]
Acceptance of user fails with message 'user alread registered' if 
[usergroupPostAccept] equals [usergroup]

This TypoScript Constants setting is not working:
  plugin.tx_sfregister.settings {
    usergroup = 7
    usergroupPostSave = 8 
    usergroupPostConfirm = 9
    usergroupPostAccept = 7
  }

Workaround: 
If I used a different usergroup (10) for usergroupPostAccept  it is working.

**Comment by garbast** [comment]
That is correct, you cant define the same usergroup in two different steps. That is not an error in the code but in the configuration.

**Comment by g-nebel** [comment]
I can't find this in the documentation. 
Also the usergroup [usergroup ] seems not to be used but required.

**Comment by garbast** [comment]
usergroup is used if no confirmation is required. So it is only required if you need no double optin.

https://github.com/evoWeb/sf_register/blob/9cca5dcd0464023518653ffd58e33feb1242ca49/Classes/Controller/FeuserCreateController.php#L98
