### ISSUE TITLE
Missing translations can cause errors

### ISSUE THREAD

**Issue by millenialcoder25** [evoWeb/sf_register#148]
TYPO3 10.4.17
sf_register 10.1.5

Missing Translations for german (and I think french and dutch as well [didn't test yet]) causes an localization error in \TYPO3\CMS\Extbase\Utility\LocalizationUtility because no matching translation was found and no fallback was set. You can reproduce them by using the invite plugin at an instance with german as default language and sending an invitation via frontend. 

![image](https://user-images.githubusercontent.com/43237925/127549958-c60514b7-f675-4c52-89b5-4ba1db320a73.png)

**Comment by garbast** [comment]
You are welcome to provide a PR with the missing labels.

**Comment by garbast** [comment]
Closed due to lack of activity for more then 30 days.
