### ISSUE TITLE
Error class call in exception handling when render the body part of an mail template

### ISSUE THREAD

**Issue by millenialcoder25** [evoWeb/sf_register#150]
TYPO3 10.4.17
sf_register 10.1.5

I defined a wrong path to my mail template, but the error was thrown by symfony mailer because of a missing html body in mail when trying to send it. After a little troubleshooting I came to my mistake with the wrong path but a more explicit error message would have been helpful. During that I catched a wrong call of the Fluid InvalidTemplateResourceException in the following two exception handlings in Services/Mail because of a backslash at the beginning: 

![image](https://user-images.githubusercontent.com/43237925/127553067-179ac10e-b6d6-4b9a-bda6-2a5c6a5aaa1d.png)

Removing them leaded to a "correct" error message because of my wrong template path.

**Comment by garbast** [comment]
Sorry, but the leading backslash is required, else the exception is searched in the namespace, where it does not exist.

See https://www.php.net/manual/de/language.namespaces.global.php#117276

Exception != \Exception
