### ISSUE TITLE
Exception after validating create form

### ISSUE THREAD

**Issue by swilking** [evoWeb/sf_register#154]
TYPO3 version: 11.5.3
sf_register: 11.0.0

On submitting a create form with validation errors (i.e. empty fields or different passwords) an Exception occured:

Call to a member function getUid() on array

private/typo3conf/ext/sf_register/Classes/Controller/FeuserCreateController.php line 48

/** @var FrontendUser $userData */
$userData = $this->request->hasArgument('user') ?
    $this->request->getArgument('user') :
    $originalRequest->getArgument('user');
if ($userData->getUid()) {
    $userData->_setProperty('uid', null);
}

**Comment by swilking** [comment]
This fix work for me:

Replace 

if ($userData->getUid()) {

with

if ($userData instanceof FrontendUser && $userData->getUid()) {

**Comment by garbast** [comment]
How about a Pull Request?

**Comment by swilking** [comment]
Done, but linking to the issue doesn't work

**Comment by cehret** [comment]
same with edit form. I created a [pull request](https://github.com/evoWeb/sf_register/pull/158)

**Comment by garbast** [comment]
Merged
