### ISSUE TITLE
captcha not working (sr_freecap and recaptcha)

### ISSUE THREAD

**Issue by blueamerican** [evoWeb/sf_register#16]
typo3 6.2.25
sf_register 6.2.8

For me both captchas are not working.

With sr_freecap, no input box is shown.
with jm_recaptcha (new google and legacy captcha) it is impossible to send the register form. always this error comes:
Der eingegebene Verifizierungscode stimmt nicht mit dem Angegebenen überein.

best regards
m

**Comment by garbast** [comment]
The focus on implementing a captcha is, due to time restrictions, only limited to ext:recaptcha. If you can provide patches for the sr_freecap or jm_recaptcha feel free to send PRs.
