### ISSUE TITLE
Required argument "user" is not set for Evoweb\SfRegister\Controller\FeuserEditController->save

### ISSUE THREAD

**Issue by Solution97** [evoWeb/sf_register#165]
Hey,

I have the same issue as here: https://github.com/evoWeb/sf_register/issues/101

This error occurs when I paste the link with all params to an other window. I understand that when there is no form data the registration can't work. But is there a possibility to add an error message to prevent getting a typo3 exception? Would be great!

Greetings!

**Comment by garbast** [comment]
As you already said, it's a extbase error. It wouldn't be possible to use validation if the $user argument would accept null. So, no there is no solution for that.
