### ISSUE TITLE
TCA of fe_users.status should be type select instead of check

### ISSUE THREAD

**Issue by epxfrho** [evoWeb/sf_register#166]
The tca of fe_users.status is currently type of **check** with renderType **selectSingle**. There is no **selectSingle** for the type **check**. It should be type of **select** instead. Editing a frontend user throws an PHP warning _Undefined array key 1 in /var/www/html/public/typo3/sysext/backend/Classes/Form/Element/SelectSingleElement.php_ with PHP ^8.

sf_register 11.0.0
typo3 11.5.4

best regards
Frank

**Comment by garbast** [comment]
Feel free to submit a PR.

**Comment by epxfrho** [comment]
Thanks for pushing me to submit a PR. It was my first time.

**Comment by garbast** [comment]
Thanks for your work.

Nice to see, that github is eazy enough, to enable peoples to cooperate.
