### ISSUE TITLE
File.php causing PHP Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by zloy88** [evoWeb/sf_register#169]
I am using TYPO3 v11 with PHP 8.1 and the log writer is constantly writing a PHP Warning because of this file:line
PHP Warning: A non-numeric value encountered in /mnt/c/htdocs/gbait/public/typo3conf/ext/sf_register/Classes/Services/File.php line 135

This can be easily fixed if $value is casted to int before assigning new calculated values, like this:

```
protected function returnBytes($value): int
    {
        $last = strtolower(substr(trim($value), -1));
        $value = (int)$value;
        switch ($last) {
            case 'g':
                $value *= 1024 * 1024 * 1024;
                break;

            case 'm':
                $value *= 1024 * 1024;
                break;

            case 'k':
                $value *= 1024;
                break;
        }

        return (int)$value;
    }
```

**Comment by garbast** [comment]
It's fixed in develop, but i need to find time and energy to fix the tests in the release chain to release a new version.

https://github.com/evoWeb/sf_register/blob/1afcbcdc1c6840afe5f1a9b7341e3a2d4ee56df6/Classes/Services/File.php#L129
