### ISSUE TITLE
Error on user registration

### ISSUE THREAD

**Issue by richyr45** [evoWeb/sf_register#170]
On TYPO3 11.5.3 there occurs an error when trying to register as new user:

Call to a member function getUid() on array in /html/typo3/typo3conf/ext/sf_register/Classes/Controller/FeuserCreateController.php line 48

**Comment by garbast** [comment]
Ist already fixed in develop https://github.com/evoWeb/sf_register/blob/1afcbcdc1c6840afe5f1a9b7341e3a2d4ee56df6/Classes/Controller/FeuserCreateController.php#L48
