### ISSUE TITLE
[BUG] On Registration: A message must have a text or an HTML part or attachments.

### ISSUE THREAD

**Issue by linawolf** [evoWeb/sf_register#176]
evoweb/sf-register (dev-develop 4a4fbeb)
TYPO3 11.5.4

As you suggested in https://github.com/evoWeb/sf_register/issues/175 I am using dev-develop now. On Registration I now get the error:

(1/1) Symfony\Component\Mime\Exception\LogicException
A message must have a text or an HTML part or attachments.

After debugging some, the code is trying to use EXT:sf_register/Resources/Private/Templates/Email/NotifyUsercreateConfirm.html as Standalone view. However the File is called NotifyUserCreateConfirm.html (Note the capital C)

**Comment by Apen** [comment]
Seems to be linked to my comment https://github.com/evoWeb/sf_register/issues/175#issuecomment-1009705800
A var is now in lower case and was before upper.

**Comment by garbast** [comment]
This is fixed with  commit b2cd4cc
