### ISSUE TITLE
[BUG] sf_register reorders the new content element wizard

### ISSUE THREAD

**Issue by linawolf** [evoWeb/sf_register#179]
SF-Register is installed:
![WithSfRegister](https://user-images.githubusercontent.com/48202465/149117592-b3939aaf-9990-4661-945e-a5bd5e7967a5.png)

SF-Register is not installed:
![Without](https://user-images.githubusercontent.com/48202465/149117604-3b6ee84c-4a7e-4a77-8781-9f51b833fa42.png)

Could we maybe just handle it like grid-elements if an own tab is really necessary?

**Comment by garbast** [comment]
Not much i can do there. See here
https://github.com/evoWeb/sf_register/blob/develop/Configuration/TSconfig/Wizards/NewContentElement.typoscript
Beside in 10.x it was the same and didnt changed the order. Seems to me as if the sf_register ist loaded before the EXT:frontend

Could you please test localy, what happens if you comment out the line `after = plugins`

**Comment by linawolf** [comment]
It might have something to do with https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Important-95647-ComposerInstallationsAndExtensionUsage.html and the removal of the packages states. Frontend should be required by sf_register in the composer.json:

<pre>

	"require": {
		"typo3/cms-core": "^11.5",
		"typo3/cms-extbase": "*",
		"typo3/cms-fluid": "*",
		"typo3/cms-frontend": "*"
	},
</pre>

However this seems to have no effect on the loading order of the TSconfig in the ext_localconfig.php. I suspect a Core bug here.

**Comment by garbast** [comment]
I asume a bug in the core too. Beside, i cant reproduce the problem in my 11.5.3 the order of the tabs are:
- Typical page content
- Form elements
- Menu
- Plugins
- Special elements
- User registration
I leave the issue open as reminder to debug how the core is loading the tsconfig at a later time.

**Comment by linawolf** [comment]
what does your composer.json look like? I will try if I can reproduce it in a clean project

**Comment by garbast** [comment]
It is basically this:

```
{
  "name": "evoweb/dev11",
  "repositories": [
    {
      "type": "path",
      "url": "./packages/*"
    },
    {
      "url": "https://github.com/garbast/static_info_tables.git",
      "type": "git"
    },
    {
      "url": "https://github.com/garbast/oauth2.git",
      "type": "git"
    }
  ],
  "require": {
    "typo3/cms-core": "^11.5",

    "typo3/cms-backend": "*",
    "typo3/cms-extbase": "*",
    "typo3/cms-extensionmanager": "*",
    "typo3/cms-filelist": "*",
    "typo3/cms-fluid": "*",
    "typo3/cms-frontend": "*",
    "typo3/cms-install": "*",
    "typo3/cms-recordlist": "*",

    "typo3/cms-adminpanel": "*",
    "typo3/cms-belog": "*",
    "typo3/cms-beuser": "*",
    "typo3/cms-felogin": "*",
    "typo3/cms-fluid-styled-content": "*",
    "typo3/cms-form": "*",
    "typo3/cms-info": "*",
    "typo3/cms-lowlevel": "*",
    "typo3/cms-recycler": "*",
    "typo3/cms-reports": "*",
    "typo3/cms-rte-ckeditor": "*",
    "typo3/cms-seo": "*",
    "typo3/cms-setup": "*",
    "typo3/cms-t3editor": "*",
    "typo3/cms-tstemplate": "*",
    "typo3/cms-scheduler": "*",

    "helhum/typo3-secure-web": "*",
    "helhum/typo3-console": "*",
    "typo3/cms-styleguide": "*",

    "gridelementsteam/gridelements": "dev-master",
    "evoweb/store-finder": "dev-develop",
    "evoweb/recaptcha": "dev-develop",
    "evoweb/extender": "dev-develop",
    "evoweb/sf-register": "dev-develop",
    "evoweb/imagemap": "dev-develop",
    "evoweb/sf-books": "dev-develop",
    "evoweb/sessionplaner": "dev-develop",
    "evoweb/ew-llxml2xliff": "dev-develop",
    "mfc/oauth2": "dev-latest"
  },
  "config": {
    "platform": {
      "php": "7.4.1",
      "ext-gd": "7.4"
    },
    "preferred-install": {
      "typo3/cms-*": "source",
      "evoweb/*": "source",
      "mfc/oauth2": "source",
      "*": "dist"
    }
  },
  "extra": {
    "typo3/cms": {
      "root-dir": "private",
      "web-dir": "public"
    }
  }
}
```

**Comment by linawolf** [comment]
removing the line  `` after = plugins``  from the pageTSconfig and adding typo3/cms-frontend as requirement in the composer.json solves the problem for me.

**Comment by linawolf** [comment]
I can also solve it by unsetting the after property in my PageTSconfig (Page properties of rootpage ->Resources -> Page TSconfig )
```
mod.wizards.newContentElement.wizardItems.sf_register.after >
```
In case anyone else has the problem.
