### ISSUE TITLE
[BUG] Validation of all fields is not working in v11

### ISSUE THREAD

**Issue by haithem-daoud** [evoWeb/sf_register#181]
Hello,

I'm using TYPO3 V11, sf_register dev-develop, PHP 8.0

When I try to create a new user, validation.create is not working.

NOTE: When I use dev-master branch validation works.

**Comment by garbast** [comment]
Using TYPO3 11.5.5, sf_register dev-develop and PHP 8.1.1 i can't reproduce the problem. Need PR if something should be fixed.

**Comment by Apen** [comment]
I think i have the same problem, it is another side effect of the new $controller var who is in upper case.

In your method `initializeActionMethodValidators()` you use `$this->settings['validation'][$this->controller]`.
This will get "validation.Create" but we put "validation.create" in typoscript.

**Comment by haithem-daoud** [comment]
@Apen Thank you for the help :)

**Comment by garbast** [comment]
Release will be pushed on tuesday

**Comment by garbast** [comment]
Release 11.1.2 is pushed
