### ISSUE TITLE
Change password throws exception

### ISSUE THREAD

**Issue by woemar** [evoWeb/sf_register#187]
Changing a users password via sf_register plugin does throw an exception.

Affeted version:
master

Setup:
Create page with plugin sf_register_password, selected fields = clear, password, passwordRepeat, submit

How to reproduce:
Login as FE user and access change password page

Error:
(1/1) #1195815178 TYPO3\CMS\Extbase\Mvc\Exception\NoSuchArgumentException
An argument "user" does not exist.

**Comment by woemar** [comment]
Added possible solution https://github.com/evoWeb/sf_register/pull/188

**Comment by garbast** [comment]
#188 is merged
