### ISSUE TITLE
TypoScript conf for user groups in various steps

### ISSUE THREAD

**Issue by zoranilic** [evoWeb/sf_register#189]
sf_register V10.1.7
TYPO3 V10.4.23
I think, and I didn't find anywhere in documentation, that there is a guideline for "UserGroupIdSettings" how it should be used. Please correct me if I'm wrong with this lack in a documentation.
TS configuration for:
```
plugin.tx_sfregister.settings {
        usergroup = 0
        usergroupPostSave = 1
        usergroupPostConfirm = 2
        usergroupPostAccept = 0
}
```
These 4 configurations MUST HAVE DIFFERENT USER GROUPS DEFINED.
It isn't written anywhere that there should be min 4 groups added in BE if you want to have values for all 4 configurations and that all 4 must have different user groups assigned.
Current example above is configuration if you want to have 1 user group upon registration saved and after user confirms registration.
If any of these other configurations have the same user group ID, the logic won't be as you expect as admin or developer user of your extension.
If you set, by any reason, the conf like the fallowing, It won't change user group after user confirms registration:
```
plugin.tx_sfregister.settings {
        usergroup = 2
        usergroupPostSave = 1
        usergroupPostConfirm = 2
        usergroupPostAccept = 2
}
```

**Comment by garbast** [comment]
First, you dont need all of these settings.
- usergroup is only needed if you do not have double opt in active (aka bad user experience)
- usergroupPostAccept is only needed if you need an admin to confirm every registration

So this leaves you with only two needed groups usergroupPostSave  and usergroupPostConfirm.

As the extension is open source, it would be great, if you could push an PR with changes to the documentation, covering the needed configuration.

**Comment by zoranilic** [comment]
I will as soon as I can.
Just to help the wondering admins and editors when this could be an issue.
If you have a default configuration in file system and want to overwrite TypoScript configuration somewhere else in file system or in back-end this could be a problem. So, pay attention to all 4 UIDs conf, not overwrite just one somewhere.
