### ISSUE TITLE
Image field in edit form causes an error (TYPO3 11.5.5)

### ISSUE THREAD

**Issue by patrickdadzio** [evoWeb/sf_register#190]
If you add the Image field to an Edit form (sfregister_edit) and you open the page in the frontend it will cause an error:

 #1253036401 TYPO3Fluid\Fluid\Core\ViewHelper\Exception
Argument "accept" has already been defined, thus it should not be defined again.

The error disappears if you delete line 87 from UploadViewHelper.php:
$this->registerTagAttribute('accept', 'string', 'Accepted file extensions.', false, '');

**Comment by garbast** [comment]
Please check if this problem is solved in the current develop branch.

**Comment by garbast** [comment]
Closed due to lack of activity.

**Comment by Xippo** [comment]
Got the same error, actual develop branch works fine. We created a specific patch for the UploadViewHelper file and we patch this over composer in die deployment pipeline. This one 58873a62964a20ebc7407a97fb43c5046fbbec91 fixed the error
