### ISSUE TITLE
Mails won't sent when SMPT settings are used

### ISSUE THREAD

**Issue by AKaravas** [evoWeb/sf_register#191]
Hello, 

i am using all-inkl as a webhoster for a website. Sadly, sendmail is not installed on their servers, so i created an new mail account and it works with smtp. I added the settings on my TYPO3 installation (11.5.5) and i tested if the mail can be sent with TYPO3's test function under the Envornment Module. TYPO3 successfully sent the email. To make sure that i did everything correct, i entered the wrong username on my smtp settings and TYPO3 could NOT send the mail because it could not authenticate the smtpserver. Which means i entered all the information correctly. Now, if i try to register a user, i am waiting for the confirmation mail but i never get one. Why is this happening? The MailMessage class should be able to send the mails regardless the protocol used. I might have a misconfiguration on my system. This is what i have and i am expecting to get a confirmation mail to activate the account:

```
 settings {
        confirmEmailPostCreate = 1
        autologinPostConfirmation = 1
        autologinPostRegistration = 0
        usergroupPostSave = 1
        usergroupPostConfirm = 2
        usergroupPostAccept = 3
        usergroup = 3
        useEmailAddressAsUsername = 0
        sitename = My Sitename
        notifyUser {
            createConfirm = 1
            createAccept = 1
            editSave = 1
            editConfirm = 1
        }
        userEmail {
            fromName = My Sitename
            fromEmail = no-reply@my-site.com
        }
        adminEmail {
            fromName = My Sitename
            fromEmail = no-reply@my-site.com
            replyName = My Sitename
            replyEmail = no-reply@my-site.com
            toName =To some name
        }

    }
```

**Comment by garbast** [comment]
What TYPO3, PHP and extension version are you using?

**Comment by AKaravas** [comment]
I use TYPO3 11.5.8 and the newest version of the extension. I thought i was doing something wrong with the configuration and i just configured every setting i could find. I then got an error that the LocalizationUtility could not find the translation key, which is strange because the key was present. I think it could not find the translation key for the confirmation subject. I debugged the position where the LocalizationUtility called the key, and it returned NULL althought it exists. At this point i never got to the mail, because TYPO3 threw an error and broke the action there

**Comment by garbast** [comment]
What PHP version are you using? Seems to me like it could be a problem with PHP 8.1

If the key returns a NULL the translation is not present. Could you tell me what the debugger use as key which returns NULL?

**Comment by garbast** [comment]
I tested your configuration with the latest develop branch. Could you please confirm, if that fixes your problem too?

**Comment by SMA-cgn** [comment]
Did you find the root cause?
Also in my environment it does not send any mails when the maximal template is included. Using the minimal template everything works fine!
I am using the latest dev version, php 8.0 & typo3 11.5.14.

**Comment by SMA-cgn** [comment]
Hi, I tested it with the latest dev release. For me everything works just fine! Not sure if I did something wrong or if the new release did it. Thanks a lot! Great extension!
I documented the constants a little bit for me. Maybe this could be documented centrally in constant manager or in the ext documentation.

```
### Configuration of sf_register for frontend user registration
plugin.tx_sfregister.settings {
	# General settings
  		# uses email adress as username (email adress written into field username)
  		useEmailAddressAsUsername = 0
  		sitename = 
  		# site name used in email subject - thanks for registering at ...
  		emailSitename = 
  		useEncryptedFilename = 0
  		captchaId = 
		redirectPostRegistrationPageId = 
		redirectPostActivationPageId = 
		redirect.page = 
  	# Assigned user groups
  		# assigned user group after saving user data on website by user
  		usergroupPostSave = 2
  		# assigned user group after confirmation of user registration by user (via email link)
        usergroupPostConfirm = 1
  		# assigned user group after acceptance of user registration by admin (via email link)
        usergroupPostAccept = 1
  
	# Required confirmations by mail
  		# Required confirmation of registration by user after user registered on website (via email link)
  		# works
		confirmEmailPostCreate = 1
  		# Required acceptance of user creation by admin after user creation by user (via email link)
  		acceptEmailPostCreate = 0
		# Required confirmation of registration by user after admin accepted registration (via email link)
  		confirmEmailPostAccept = 0
  		# Required acceptance of registration by admin after user confirmed registration (via email link)
		acceptEmailPostConfirm = 0
  		# Required confirmation of user data change by user (via email link)
		confirmEmailPostEdit = 0
		# Required acceptance of user data change by admin after user confirmed data change (via email link)
  		acceptEmailPostEdit = 0  

  	# Autologin settings
  		# automatic login of user, after confirmation of registration by user
  		# works
        autologinPostConfirmation = 1
        autologinPostRegistration = 0

	# Notification of user on certain events
        notifyUser {
  			createSave = 1
			createRefuse = 0
          	createConfirm = 1
            createAccept = 1
			createDecline = 0
          	editSave = 1
            editConfirm = 1
			editAccept = 0
			inviteInvite = 0
        }
		# Notification of user on certain events
		notifyAdmin {
			# notifies admin, when user saves data on registration / feuser record is created
          	# works
          	createSave = 1
         	# notifies admin, when user confirmed registraion via email link
			createConfirm = 1
			createRefuse = 0
			createAccept = 0
			createDecline = 0
          	# notifies admin, when user deletes account
			deleteSave = 0
          	# notifies admin, when user cofirms mail to finally delete account
			deleteConfirm = 0
			deleteSendLink = 0
			editSave = 0
			editConfirm = 0
			editAccept = 0
			inviteInvite = 0
			resendMail = 0
        }
        userEmail {
            fromName = 
            fromEmail = 
        }
        adminEmail {
            fromName = 
            fromEmail = 
            replyName = 
            replyEmail = 
            toName = 
            toEmail = 
        }
	}

```

**Comment by garbast** [comment]
All constants are documented with translation labels https://github.com/evoWeb/sf_register/blob/develop/Resources/Private/Language/locallang_ts.xlf and are documented e.g. https://github.com/evoWeb/sf_register/blob/develop/Documentation/Configuration/Emails/Index.rst
