### ISSUE TITLE
Compatibility for PHP 8.1

### ISSUE THREAD

**Issue by moritzkiehl** [evoWeb/sf_register#197]
The extensions seem to not work with PHP 8.1. Most of the forms seem to throw error when used with PHP 8.1. This seems to also be connected to  #193.

**Comment by garbast** [comment]
I fixed a lot of typing problems. Please have a look if the problems in your setup are solved.

**Comment by liveman1** [comment]
Hi,
is this extension supposed to work with PHP 8.0?
Thanks

**Comment by schmitzal** [comment]
Any news when this will be released?
Is there anything we can support you or something what needs some testing?

**Comment by moritzkiehl** [comment]
> I fixed a lot of typing problems. Please have a look if the problems in your setup are solved.

Sry for answering so late since a coworker took over the project. I think I can take a look at the end of this or the beginning of next week.

**Comment by garbast** [comment]
Call me picky, but i think the week is long over. Could you please test the changes, you requested.

**Comment by moritzkiehl** [comment]
Hi im very sorry. I forgot this totally... I will check it today.

**Comment by moritzkiehl** [comment]
@garbast So I replaced the package version in our Project and checked multiple forms and everything seems to work. The changes you made include also everything (and more) we did when we added the extension as a local package.

So from my point of view, everything looks good.

And again I am very sorry that I forgot to test/give feedback.

**Comment by PaDa19** [comment]
Hello,

I am currently upgrading a website to TYPO3 11 and noticed that when I try to remove the profile picture I get a 503 error message. 

The get parameters: ?tx_sfregister_edit[action]=preview&tx_sfregister_edit[controller]=FeuserEdit&cHash=73739042ea83846ca635df85eca6866e

Here is what I found in the log file:

`Thu, 19 Jan 2023 03:16:04 +0100 [CRITICAL] request="51d688a76d1bf" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: FE): TypeError, code #0, file /var/www/www.diedomain.de/htdocs/dev/typo3_src-11.5.21/typo3/sysext/extbase/Classes/Http/ForwardResponse.php, line 52: Argument 1 passed to TYPO3\CMS\Extbase\Http\ForwardResponse::withExtensionName() must be of the type string, null given, called in /var/www/www.diedomain.de/htdocs/dev/www/typo3conf/ext/sf_register/Classes/Controller/FeuserController.php on line 381 -`

The profile picture gets deleted and I can upload a new one.

**Comment by garbast** [comment]
@PaDa19 could you please test what happens, if you replace

```->withExtensionName($referringRequest->getControllerExtensionName())```

with

```->withExtensionName('sf_register')```

**Comment by PaDa19** [comment]
Hello,

thanks for getting backt o me.

It gives me this error:

Sun, 22 Jan 2023 13:32:39 +0100 [CRITICAL] request="aa7aa03e7c698" 
component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: 
Exception handler (WEB: FE): 
TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException, code 
#1278450972, file 
/var/www/www.diedomain.de/htdocs/dev/typo3_src-11.5.21/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php, 
line 101: Class  does not exist. Reflection failed. - 
{"mode":"WEB","application_mode":"FE","exception_class":"TYPO3\\CMS\\Extbase\\Reflection\\Exception\\UnknownClassException","exception_code":1278450972,"file":"/var/www/www.diedomain.de/htdocs/dev/typo3_src-11.5.21/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php","line":101,"message":"Class 
does not exist. Reflection 
failed.","request_url":"https://www.diedomain.de/forum/profilbild-bearbeiten?tx_sfregister_edit%5Baction%5D=preview&tx_sfregister_edit%5Bcontroller%5D=FeuserEdit&cHash=73739042ea83846ca635df85eca6866e","exception":null}

I already checked what the method 
->widthExtensionName(|$referringRequest->getControllerExtensionName()|) 
returns in TYPO3 10. It returned 'SfRegister'. When I tried to replace 
the line with |->withExtensionName('||SfRegister') in TYPO3 11 it also 
gave me the same error.|

|Kind regards,
Patrick.
|

|
|

|
|


Am 22.01.2023 um 13:25 schrieb Sebastian Fischer:

**Comment by evoWeb** [comment]
Image handling is fixed in 27193188af2f72d3b41057411b6ee08bd02b4804

Could someone please confirm this? I would release it afterwards.
