### ISSUE TITLE
Failing to extend with new field

### ISSUE THREAD

**Issue by abvdveen** [evoWeb/sf_register#198]
I have an issue that seems similar to #124 but is not related to the naming of the field:

`Exception while property mapping at property path "": Property "ageGroup" was not found in target object of type "Evoweb\SfRegister\Domain\Model\FrontendUser".`

When I add the get and set directly to the FrontendUser model in sf_register/Classes/Domain/Model/FrontendUser.php I get no error, so it seems the extended model is not loaded.

This is my modified ew_sfregister_extended ext_localconf.php:

`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sf_register']['extender'][\Evoweb\SfRegister\Domain\Model\FrontendUser::class]['ew_sfregister_extended'] =
	'EXT:ew_sfregister_extended/Classes/Domain/Model/FrontendUser.php';`

And ew_sfregister_extended/Classes/Domain/Model/FrontendUser.php starts with:

`namespace Evoweb\EwRegisterExtended\Domain\Model;
use TYPO3\CMS\Extbase\DomainObject\AbstractEntity;
class FrontendUser extends AbstractEntity`

Any idea what's going wrong? Using sf_register 11.1.3, extender 8.1.0.

I'm currently upgrading this site, in the previous it's working, using sf_register 9.4.1 and extender 6.6.3

**Comment by abvdveen** [comment]
Sorry, found it: had to replace EXTCONF with EXTENSIONS in $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sf_register']['extender']...

Had looked at the documentation of 'extender', but [this](https://docs.typo3.org/typo3cms/extensions/extender/stable/Index.html) link on your GitHub page goes to version 6.6.0, which I overlooked.
And of course there is no notion of this change, as it wasn't in that version :)

**Comment by garbast** [comment]
Changed link to documentation in extender readme. Thanks for hinting.
