### ISSUE TITLE
Support of modals

### ISSUE THREAD

**Issue by liveman1** [evoWeb/sf_register#201]
Hi, I would like to use sf_register in a modal. When creating a new user & selecting 'create' the modal is hidden. Opening the modal again enables to review the user data and to complete the registration.
Is the there any way to keep the modal opened during the registration process?
Thanks a lot

**Comment by garbast** [comment]
Sorry to say, but that is not a feature by sf_register, but was added by your own template. So you need to figure out to modify your javascript to reopen the modal.

**Comment by garbast** [comment]
The templates are overrideable. All links that are used (e.G. creation form url, or account confirmation url in email) can be modified to your needs. the only link that is not modifiable to contain the anchor is the redirect on auto login.

Did i miss any location, that is out of your scope to be modified?

**Comment by SMA-cgn** [comment]
Thanks a lot!

I added this javascript in order to open the modal, if the URL contains "?tx_sfregister".

```
//show modal with id=modal-6, if url contains "?tx_sfregister"
document.addEventListener("DOMContentLoaded", function() {
        if (window.location.href.indexOf("?tx_sfregister") > -1) {
                var myModal = new bootstrap.Modal(document.getElementById('modal-6'));
                //var myTab = new bootstrap.Tab(document.getElementById('tab-13'));
                myModal.show();
                });
        }
});
```
