### ISSUE TITLE
Overwrite Password-Meter (PasswordStrengthCalculator)

### ISSUE THREAD

**Issue by MoppieMop** [evoWeb/sf_register#202]
I would like to overwrite the password meter to be only green if the password matches all criteria (defined in regex).
The question is now: how can I overwrite the PasswordStrengthCalculator?

**Comment by garbast** [comment]
You need to modifie the EXT:sf_register/Resources/Public/JavaScript/sf_register.js and then include your js file in TypoScript setup with page.includeJSFooter.sf_register =
