### ISSUE TITLE
Template file missing

### ISSUE THREAD

**Issue by heural** [evoWeb/sf_register#204]
The template file 
ext/sf_register/Resources/Private/Partials/Preview/Resend.html
is missing in 11.1.3

**Comment by garbast** [comment]
Why would you need that? Partials/Preview/* only contains previews for FIELDS not actions. So in what condition do you have problem with such a file missing?

**Comment by heural** [comment]
However,  if you choose a email-field and the "resend submit button" in the plugin config for the Form fields, then this action is taken.
So I misunderstood and maybe only the resend button should taken?

**Comment by garbast** [comment]
In what plugin did you set the resend submit button?
