### ISSUE TITLE
invite does not work

### ISSUE THREAD

**Issue by averlon** [evoWeb/sf_register#209]
Hi,
can anyone give me an hint how invite works.
I have created the invite plugin as content on a page.
Only Fields:

- Email to send Invitation
- Privacy Statement
- Captcha
- Change Button
- Submit Button

The page itself has access: show at any login

There is no eMail sent!
There is no user created!

What could I do to get it working!
Regards
Kallewirsch

By the way: Using Terms and Conditions creates an error!

**Comment by garbast** [comment]
Invite does not create an user entry in the database because of privacy concerns.
Terms and Conditions can not be accepted by the invitand but only by the invitee.

The email uses the same logic as all the other controllers. Please check your mail configuration. If the mails are send on registration, the invite controller should be able to send the invite mail too.

**Comment by averlon** [comment]
Hi,
I see,
but - yes, "should behave as the others", but since the others send e-Mails and invite does not, I am probably still on the wrong tracke.
And yes, sure, Term and Conditions only by the invitand, but it creates an crash - at least in my case. Probably I have misconfigured T&C somehow. But simply what can I do as only select the field in the BE form. And when doing so, it crashes with an T3 error.
I will test it again an post the logfile entry.

**Comment by evoWeb** [comment]
So after testing it localy i can say, that the gtc field does not crash my rendering and that the invitation mail gets send.

**Comment by averlon** [comment]
Hi,
took some time until I was able to test.
I have created the content element on a page from scratch.

Two situations:
1) when logged in: no e-Mail sent and no user stored in the user-folder.

2) when not logged in:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of Evoweb\SfRegister\Services\Mail::getSubject() must be of the type string, null returned | TypeError thrown in file /var/www/html/averlon.de/av_homep/public/typo3conf/ext/sf_register/Classes/Services/Mail.php in line 129. Requested URL: http://www.averlon.com/com-intern/com-invite?tx_sfregister_invite%%5Baction%%5D=invite&tx_sfregister_invite%%5Bcontroller%%5D=FeuserInvite&cHash=35469071a3ff0c1517e068fcb43ef9e4

I will try to investigate some more details.
