### ISSUE TITLE
invite - message "Das Feld NutzerId war nicht leer obwohl es hätte sein müssen"

### ISSUE THREAD

**Issue by averlon** [evoWeb/sf_register#218]
Hi,
still struggling with invite.

In the STANDARD setup of invite, the field "username" is not visible.

Prerequisite: User is logged in!

When I then fill in the e-Mail address of the invitee, tick the gtc and fill the captcha the response shows the message:
"Das Feld NutzerId war nicht leer obwohl es hätte sein müssen".

I was able to get it working when the user is not (!!not!!) logged in.
In the Message sent via e-Mail then 
`User "" send an invitation to`
That was the reason I assumed the must have to be logged in.

So I have a problem with both - logged in and not logged in!

Can you give me some help?

`
validation.invite {
     username >
     invitationEmail {
      1 = "Evoweb.SfRegister:Required"
      2 = "EmailAddress"
    }
    captcha = "Evoweb.SfRegister:Captcha", options={"type": "{$plugin.tx_sfregister.settings.captchaId}"}
  }
`

**Comment by garbast** [comment]
Once the user is logged in, the field username may never be filled to prevent renaming.

In your case, you could use the InviteInviteEvent to add the feuser information to the controller settings and use these for the mail content rendering.
