### ISSUE TITLE
Email Confirmation is not working

### ISSUE THREAD

**Issue by Lumrenion** [evoWeb/sf_register#22]
### Process: User needs to confirm their email address.
Setting both **notifyUserPostCreateSave** and **confirmEmailPostCreate** to 1, 
- the user will be in Usergroup usergroupPostSave and disabled -> this works correctly 
- an Email should be sent to the user, which contains the link to activate their account -> this does not happen, instead the email says, that the account is now available

### Process: Admin needs to accept the newly created user.
Setting both **notifyAdminPostCreateSave** and **acceptEmailPostCreate** to 1,
- the user will be in usergroup usergroupPostSave and disabled -> this works correctly
- an Email should be sent to the admin, which contains the link to activate the user account -> this does not happen, instead the email says

### Process: Neither email confirmation nor admin activation is required
Setting **none** of the above combinations, 
- the user should not be disabled and is in group usergroupPostConfirm/usergroupPostAccept/usergroup -> this, again, works correctly
- the user should get an email, which says, that the account is available -> Instead, the user gets an email with an activation link. Klicking on it, the message appears, that the user account is already activated.

Conclusion: In FeuserCreateController->saveAction the wrong emails are sent to admin and user, most likely because the $type variable contains the wrong value.

**Comment by garbast** [comment]
There is not realy an error in the saveAction. Please be aware, that you need notifyUserPostCreateConfirm active too. PostCreateSave only indicated that an email should be send and in case you use confirmEmailPostCreate the notifyUserPostCreateConfirm needs to be checked too.

Example:
plugin.tx_sfregister.settings.confirmEmailPostCreate = 1
plugin.tx_sfregister.settings.notifyUserPostCreateSave = 1
plugin.tx_sfregister.settings.notifyUserPostCreateConfirm = 1
plugin.tx_sfregister.settings.usergroupPostSave = 2144
plugin.tx_sfregister.settings.usergroupPostConfirm = 2145

**Comment by Lumrenion** [comment]
Thank you. I think, I now understand how the usergroups are working for this extension.
One thing I forgot to mention: For the first process, I did set notifyUserPostCreateConfirm. But the User gets the wrong email notification. The Email that is sent to the user does not contain a confirmation link.
For the third process, there should not be a confirmation link in the email, but there is.

So either this issue is not closed yet or I get something totally wrong.
