### ISSUE TITLE
Return value of Evoweb\SfRegister\Domain\Model\FrontendUser::getModuleSysDmailCategory() must be an instance of TYPO3\CMS\Extbase\Persistence\ObjectStorage, null returned

### ISSUE THREAD

**Issue by MiladinBojic** [evoWeb/sf_register#220]
Hi, 

if user creates account, that needs to be accepted from an admin, 
on first click on the link in the admins email, there is no problem, the user is activated.

But, if the admin clicks on the same link again (by accidant), there is an error
`Return value of Evoweb\SfRegister\Domain\Model\FrontendUser::getModuleSysDmailCategory() must be an instance of TYPO3\CMS\Extbase\Persistence\ObjectStorage, null returned`

He schould get an Answer "The user already activated".

TYPO3 Version: 11.5
evoweb/sf-register: 8.1.0
evoweb/extender: 8.1.0

extender used to extend fe_user with one more field, not related to moduleSysDmailCategory.
Evtl. this is an issue on the side of extender extension?

Any help? Please.
Miladin.

**Comment by garbast** [comment]
Could you please check if the develop branch is working for you?

https://github.com/evoWeb/sf_register/commit/5003d70ba17eb26e011193de72e3e97005b87cd8 should have fixed that problem.

**Comment by MiladinBojic** [comment]
Perfect! Now it works as suggested. Thx!
