### ISSUE TITLE
[RELEASE] 11.1.4 for TYPO3 CMS 11

### ISSUE THREAD

**Issue by thommyhh** [evoWeb/sf_register#223]
There are some bugs in 11.1.3 regarding object initialization. Those have been fixed in the development branch. https://github.com/evoWeb/sf_register/commit/5003d70ba17eb26e011193de72e3e97005b87cd8 seems to be the last commit not mentioning TYPO3 CMS 12. Please use this to create a version 11.1.4, containing the bugfixes for TYPO3 CMS 11.

Thanks in advance.

**Comment by tobikummer** [comment]
Also [this commit](https://github.com/evoWeb/sf_register/commit/b9dd9a6fef54a1d5b059511405092a1191c415eb#diff-d894124a784977d934489b48249e596e224e094f126f79d832bb69a0188e075a) would be nice to have in the next v11 release. It's necessary with PHP 8.1/8.2

**Comment by garbast** [comment]
Just for information there is a TYPO3 11 compatible branch named 11.x-dev

**Comment by garbast** [comment]
Release 11.1.5 pushed and deployed.
