### ISSUE TITLE
Image Upload does not work at all?

### ISSUE THREAD

**Issue by gpazout** [evoWeb/sf_register#230]
On my installation the image upload does not work at all.

I debugged the FeuserEditController and various functions including formAction and previewAction. My findings are:
- formAction: the image upload inside the formAction does not work
- previewAction: the attribute image inside the user is always empty: `image => protectedTYPO3\CMS\Extbase\Persistence\ObjectStorageprototypeobject (empty)`
- ImageUploadValidator: the validator passes, because the image is always empty
- The image folder 'frontendusers': the folder called 'frontendusers' for uploading images was created succesfully by the extension and has correct access restrictions (drwxrwsr-x)

Somehow the upload fails! Unfortunately I can't find where it all goes wrong...
Somewhere between the formAction and the previewAction.

Typo3 Version: 12.4.5
PHP Version: 8.1.5
evoweb/sf-register: dev-develop
evoweb/extender :  dev-develop

**Comment by garbast** [comment]
Resolved with Commit d087332
