### ISSUE TITLE
sfregister 10.1.5 Entering a new email on EditSave

### ISSUE THREAD

**Issue by rmilenov** [evoWeb/sf_register#231]
Hi there, 
i've noticed that the new email will directly be set in the database before the user accepted it.
Also the account remains active with the new email. 
acceptPostEdit ist set to '1'. 
Email postEditSave has only an activation link but not the option to refuse the change.
It poses a serious privacy issue.

**Comment by rmilenov** [comment]
typoscript 10.437

**Comment by garbast** [comment]
The TypeScript option is not acceptPostEdit but acceptEmailPostEdit
