### ISSUE TITLE
AjaxMiddleware prevents Middlewares behind sf-register-ajax

### ISSUE THREAD

**Issue by heural** [evoWeb/sf_register#237]
In [AjaxMiddleware](https://github.com/evoWeb/sf_register/blob/9d0953c272163d28f2ebe6855a36f954b627d0a7/Classes/Middleware/AjaxMiddleware.php#L58C8-L69C1) the else-block is always executed and prevents Middlewares to work behind 'sf-register-ajax' 

The code in line 58 should be
`if (GeneralUtility::_GET('ajax') != 'sf_register') {`

**Comment by garbast** [comment]
You are right, that != is the better operator, but you are also wrong that the else part is ALWAYS executed. With an empty/not present ajax parameter the if part gets executed.

**Comment by garbast** [comment]
Modified in commit 497eaee
