### ISSUE TITLE
PHP Warning: Array to string conversion in /var/www/html/vendor/evoweb/sf-register/Classes/ViewHelpers/Link/ActionViewHelper.php line 115

### ISSUE THREAD

**Issue by VivekNitsan** [evoWeb/sf_register#242]
Hey there 
i found error while **Invite user**  PHP Warning: Array to string conversion in /var/www/html/vendor/evoweb/sf-register/Classes/ViewHelpers/Link/ActionViewHelper.php line 115

TYPO3 12.4.8
PHP 8.2

**Comment by garbast** [comment]
If you can open new issues, it would be nice to give more insides for this issue.
