### ISSUE TITLE
Error on edit template - email (disabled if logged in)

### ISSUE THREAD

**Issue by quadronet** [evoWeb/sf_register#245]
The Fluid template files "/var/www/vhosts/httpdocs/typo3conf/ext/sf_register/Resources/Private/Partials/Preview/DisabledEmail.html", "/var/www/vhosts/httpdocs/typo3conf/ext/sf_register/Resources/Private/Partials/Preview/DisabledEmail" could not be loaded.

With the selected field in backend: email (disabled if logged in) the template is missing. In the folder there is no template for this function.

**Comment by garbast** [comment]
Feel free to provide a PR to fix this.
