### ISSUE TITLE
Invisible reCAPTCHA not validated

### ISSUE THREAD

**Issue by dubmosphere** [evoWeb/sf_register#248]
The invisible reCAPTCHA (field type "submit_captcha" is not validated. This is because the field name in the form doesn't match the selected field name for "submit_captcha" in FeuserController in the modifyValidatorsBasedOnSettings method.

**Comment by garbast** [comment]
Only spontanious idea is to add the captcha field to the selected fields and modify the Captcha.html partial to be empty.
