### ISSUE TITLE
Form partial checkbox : checked-attribute not working in edit-template

### ISSUE THREAD

**Issue by heural** [evoWeb/sf_register#249]
https://github.com/evoWeb/sf_register/blob/e2f35a0588fe27f92b9a2ca4702a504f90dfc723/Resources/Private/Partials/Form/Checkbox.html#L5
checked="{options.checked}" have to be {user.gtc}

But the possibility to set a "default checked" for create-form goes away ...

**Comment by garbast** [comment]
You know, that you can modify the template for your needs? The default checked feature is exactly why it is as it is.

Just extend the partials and use a if viewhelper that achieves what you need.
