### ISSUE TITLE
PHP 7 warning in userValidator::check{roperty

### ISSUE THREAD

**Issue by ruudsilvrants** [evoWeb/sf_register#25]
In PHP 7 the function structure of an override function needs to be the same.  See warning:
`Core: Error handler (FE): PHP Warning: Declaration of Evoweb\SfRegister\Validation\Validator\UserValidator::checkProperty($value, $validatorNames, TYPO3\CMS\Extbase\Error\Result $messages) should be compatible with TYPO3\CMS\Extbase\Validation\Validator\GenericObjectValidator::checkProperty($value, $validators, $propertyName) in /Web/typo3conf/ext/sf_register/Classes/Validation/Validator/UserValidator.php line 29`

**Comment by evoWeb** [comment]
You are right this is realy a problem. Previous it did not matter what parameter extending methods had given. I need to find some quiet time for a look on all method definitions.

**Comment by garbast** [comment]
Solved the issue by renaming the function to checkUserProperty in branch develop
