### ISSUE TITLE
FrontendUser::getModuleSysDmailCategory(): Return value must be of type ObjectStorage, null returned

### ISSUE THREAD

**Issue by linawolf** [evoWeb/sf_register#250]
getModuleSysDmailCategory has only ObjectStorage as return type, while $this->moduleSysDmailCategory can also be null if not initialized. This causes type errors for us

**Comment by linawolf** [comment]
[prevent_type_error.patch](https://github.com/evoWeb/sf_register/files/14930310/prevent_type_error.patch)

**Comment by evoWeb** [comment]
Could you please prepare a PR?

**Comment by garbast** [comment]
Closed due to inactivity.
