### ISSUE TITLE
[FEATURE REQUEST] Utilize PasswordPolicyValidator

### ISSUE THREAD

**Issue by moritz-ngo** [evoWeb/sf_register#251]
Since TYPO3 CMS v12, there are global configurable password policies, see
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/PasswordPolicies/Index.html

It would be great, if those password policies would be implemented, so there's a coherent and unified configuration across the TYPO3 installation for register, update password, reset password (EXT:felogin), etc.

**Comment by garbast** [comment]
Cant you just configure an additional validation with TYPO3\CMS\Core\PasswordPolicy\PasswordPolicyValidator ? This should validate your entered password once you submit the value. see https://github.com/evoWeb/sf_register/blob/f0727e18d43d39f7c2953d72ac37532ead468b9a/Configuration/TypoScript/Common/setup.typoscript#L79

**Comment by evoWeb** [comment]
Closed due to inactivity
