### ISSUE TITLE
FeuserResendController / Call to a member function getEmail() on null

### ISSUE THREAD

**Issue by Apen** [evoWeb/sf_register#252]
Hi,

I have an error with the "Resend" feature. When i display the page where the plugin is, i have the following message :
```
Call to a member function getEmail() on null
```

FeuserResendController :
![image](https://github.com/evoWeb/sf_register/assets/1135104/fcf384e8-97c9-4924-815e-60779d634ddb)

A simple working fix :
```php
if ($user !== null) {
```

With this fix, everything is working.

**Comment by garbast** [comment]
First i prevere 

$email->setEmail($user?->getEmail() ?? '');

Second if done so,you still cant resend the activation token. Beside i think you have deeper problems.

If $this->context->getAspect('frontend.user')->get('id'); returns an id that does not resolve to a user, your setup is disturbingly broken. 

And i would question if you should use the controller as it is intended. It should be used for logged in users that want to change their email address and need to get the activation email resend.

**Comment by Apen** [comment]
Ok, you're right, we didn't use this plugin correctly. 
Thanks for your feedback.
