### ISSUE TITLE
Error when using captcha

### ISSUE THREAD

**Issue by vitd** [evoWeb/sf_register#259]
Wehen using a Captha it says:

TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/vendor/evoweb/sf-register/Classes/Services/Session.php:86

This is caused by the call in the controller, i.e. FeuserCreateController, Line 142:  $session->remove('captchaWasValid');

Steps to reproduce (for ddev, and sr-freecap, but it is the same issue on the production server, or with ReCaptcha):

ddev config  --project-type=typo3 --docroot=public --php-version 8.3
ddev start
ddev composer create "typo3/cms-base-distribution:^13"
ddev typo3 setup
ddev composer req evoweb/sf-register
ddev composer req sjbr/sr-freecap

then add needed TypoScripts (sfregister/maximum and sr_freecap) to the site template.

set srfreecap as Captcha, set needed flags for sf_register to work properly (those that are claimed to be needed when placing the "Registration: create user" plugin.

PLace the "Regsitration: create user" plugin on a page, add the Captcha field to the form fields of the registration plugin. As soon as you load the page, the error occurs. 

Am I missing something?

**Comment by garbast** [comment]
In general your setup looks okay. Only advice i can give you, is to check if the constructor of the Session class gets executed and further to check if the value of $this->values in line 65 is an array.

**Comment by garbast** [comment]
With release 13.1.0 a change to the session handling was made available, that should fix this problem. Please check, if this solves your problem.

**Comment by vitd** [comment]
Sorry for the late feedback - pre-christmas-craziness. 13.1 works with srfreecap, thank you for the fast fix!
