### ISSUE TITLE
Composer installation does not work with / supply versions

### ISSUE THREAD

**Issue by AndreasA** [evoWeb/sf_register#26]
When searching for the extension the versions are missing from composer, see:
https://composer.typo3.org/satis.html#!/evoweb/sf-register

I think it is because you have branch names that look like version numbers.
Composer accepts X.X.X or vX.X.X as version numbers.

**Comment by AndreasA** [comment]
My fault seems to be missing composer.json in currently released versions.

**Comment by AndreasA** [comment]
https://github.com/evoWeb/sf_register/pull/27

**Comment by evoWeb** [comment]
Fixed with the added composer.json
