### ISSUE TITLE
PHP Error when user registrattion 

### ISSUE THREAD

**Issue by marno2703** [evoWeb/sf_register#260]
I I have latest Version on 13.4.1. Everytime a User finishes Registration the User gets 503 and I have an Error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: array_key_exists(): Argument #2 ($array) must be of type array, null given | TypeError thrown in file /usr/local/www/vhosts/xxx/webroot/typo3conf/ext/sf_register/Classes/Services/Session.php in line 86. Requested URL: https://xxx/services/registrierung?tx_sfregister_create%5Baction%5D=proxy&tx_sfregister_create%5Bcontroller%5D=FeuserCreate&cHash=550f4b406f210735a57135f49352b093

**Comment by garbast** [comment]
So i tested with the latest develop state and i cant reproduce this. You need to provide more information. What fields did you use, what PHP Version are you running on?

**Comment by marno2703** [comment]
Hi,

Fields:
Company
First name
Last name
Email
Phone
Clear line
Password
Password repeat
Clear line
Change button
Submit button

PHP 8.2.14

**Comment by garbast** [comment]
With the same fields and PHP 8.3.14 i can't reproduce it.

I have the following settings:
        'devIPmask' => '*',
        'displayErrors' => 1,
        'exceptionalErrors' => 12290,
In general the mentioned array should never be empty it gets filled in the fetch function which gets called will creating an instance.
https://github.com/evoWeb/sf_register/blob/0091aed7f9a07ae839e6c43da7433859b9787546/Classes/Services/Session.php#L54

Could you please try to debug, if this function call gets executed on your machine?

**Comment by marno2703** [comment]
Debugging in Typo3 is something from hell in my eyes...
I think - and I#m not 100% shure - this habbens, when the $key in that funtion is "captchaWasValid"

**Comment by garbast** [comment]
I'm pretty sure that the key is captchaWasValid. The problem is, that the array in which the key gets search '$this->values' should never be a non array if the normal dependency injection and instantiation of the service is properly processed.

fetch() checks if $this->values is null, if so it tries to unserialize the values stored in the session. If that leads to a non array value or the values was not present in the session the $this->value gets set to an empty array. By this it should never be possible to have anything else but an array in that variable.

Please try to put an print_r(); before and after $this->fetch(); in line 54 and check if the printed values are missing when the error appears.

**Comment by marno2703** [comment]
For me, it seems like these line are never executed...

**Comment by marno2703** [comment]
You mean this?

    public function initializeUserSessionManager(?UserSessionManager $userSessionManager = null): void
    {
        $this->userSessionManager = $userSessionManager ?? UserSessionManager::create('FE');
        $this->session = $this->userSessionManager->createFromRequestOrAnonymous(
            $this->getRequest(),
            $this->sessionName,
        );
file_put_contents("/usr/local/www/vhosts/typo3.aoda-it.de/webroot/log.txt", "1." . print_r($this, true). "\n", FILE_APPEND);
        $this->fetch();
file_put_contents("/usr/local/www/vhosts/typo3.aoda-it.de/webroot/log.txt", "2." . print_r($this, true) . "\n", FILE_APPEND);
    }

**Comment by marno2703** [comment]
btw. perhaps an important info. User is created, and email is sent.

**Comment by garbast** [comment]
No i mean in the Session service https://github.com/evoWeb/sf_register/blob/0091aed7f9a07ae839e6c43da7433859b9787546/Classes/Services/Session.php#L54

Add
print_r('hello pre');
$this->fetch();
print_r('hello post');

If hello post is missing we are up to something.

That the email gets send is an indicator, that the code before line 151 in FeuserCreateController is executed https://github.com/evoWeb/sf_register/blob/0091aed7f9a07ae839e6c43da7433859b9787546/Classes/Controller/FeuserCreateController.php#L151

What causes riddles to me is, why the exception occurs. The constructor needs to be executed all the time.

Also a idea is to remove 'implements SingletonInterface' from the 'class Session' line and flush the cache in the install tool.

**Comment by marno2703** [comment]
Hmm, sorry. Perhaps I'm to stupid for that.
I have installed the latest Version sf_register from Extension Manager.
I'm working on typo3conf/ext/sf_register/Classes/Services/Session.php
The function at Line 54 is not __construct(), it is initializeUserSessionManager(?UserSessionManager $userSessionManager = null): void
This is the place where I added debug print.
So, what am I doing wrong?

**Comment by garbast** [comment]
Hmmm. A big misunderstanding here. In the branch main the constructor is missing but the initializeUserSessionManager is present. I'll release a new version tomorrow. That should fix the problem.

**Comment by garbast** [comment]
Release 13.1.0 is out and contains the change i was assuming was already available. Please test if this release solves your problem.

**Comment by marno2703** [comment]
Now the entire website is offline.
If I can't get it debugged in 2-3 minutes, I'll unfortunately have to delete the plugin. There is no test system and I don't have time to set it up

**Comment by marno2703** [comment]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function Evoweb\SfRegister\Middleware\AjaxMiddleware::__construct(), 0 passed in /usr/local/www/vhosts/typo3.aoda-it.de/typo3_src-13.4.1/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 2839 and exactly 1 expected | ArgumentCountError thrown in file /usr/local/www/vhosts/typo3.aoda-it.de/webroot/typo3conf/ext/sf_register/Classes/Middleware/AjaxMiddleware.php in line 36. Requested URL: https://aoda.de/services/registrierung

**Comment by marno2703** [comment]
Ok, forget what I wrote. After several chache deletions it works now.

**Comment by marno2703** [comment]
So, everything tested. Everything works as expected, now. Thank you!
