### ISSUE TITLE
#1313855173: The controller "FeuserEdit" is not allowed by this plugin

### ISSUE THREAD

**Issue by MarcoWilli** [evoWeb/sf_register#28]
Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.

TYPO3\CMS\Extbase\Mvc\Exception\InvalidControllerNameException thrown in file
/is/htdocs/xxx/www/typo3_src-6.2.27/typo3/sysext/extbase/Classes/Mvc/Web/RequestBuilder.php in line 180.

.... comes up when trying to edit own fe user account data on TYPO3 6.2.27.

**Comment by garbast** [comment]
This only happens if you try to edit a fe_user on a page where the create plugin instead of the edit plugin is present. This is no error in the extension

**Comment by MarcoWilli** [comment]
Can´t confirm. On that page is only the edit and change password plugin.
Was able to solve this problem by adding 

> plugin.tx_sfregister.mvc.callDefaultActionIfActionCantBeResolved = 1

to TypoScript.
