### ISSUE TITLE
"Set realurl config by default" leads to Fatal Error

### ISSUE THREAD

**Issue by TildBJ** [evoWeb/sf_register#29]
If `sf_register.settings.setRealurlConfigByDefault` is set to TRUE, it leads to a Fatal Error combined with realurl >= v2
The reason is:
`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['decodeSpURL_preProc']`
contains an additional array, so realurl will try to call this array. 
See `\DmitryDulepov\Realurl\Decoder\UrlDecoder::callPreDecodeHooks`

**Comment by evoWeb** [comment]
The realurl code is more or less only an example. If you like you could hand in a PR that fixes the problem, but to be honost i havent touched that file for a long time. So its not realy a surprise that it does not work.

**Comment by garbast** [comment]
There was no response to my PR invite so i assume there is no interest in fixing.
