### ISSUE TITLE
Invite feature

### ISSUE THREAD

**Issue by evoWeb** [evoWeb/sf_register#3]
Hi,

just found this new powerful extbase extension :) sr_feuser_register has some nasty problems (especially rsa authentication / salted passwords, some bugs ecc.), so this could be a good alternative!

But i am missing the INVITE feature known from sr_feuser_register.

Description of the feature:
A registered FE-User fills out the registration form without entering a passwort. As email address he enters the email address of the friend he wants to invite. After confirming the invited friend receives an email were he can click to accept or decline the invitation.

Would be great if this could be implemented.

History
#1 Updated by Sebastian Fischer over 4 years ago

Status changed from New to Accepted
Comment Edit
This could be implemented by having a new controller with invite form and normal form, preview, save. On save the email gets send to the invitee. The activation link would then redirect to the normal form in which all missing data get entered. After saving the account of the invitee gets activated directly.
#2 Updated by Georg Schönweger over 4 years ago

Comment Edit
Sounds good :) This way the person who invites (let's call him "inviter") doesn't have to fill out all required fields. The invitee will fill them out later by clicking on activation link.

But what if all required fields are already filled out by the "inviter"? Then IMO the activation link should activate directly the fe-user and just display a message "Your account has been activated. To change your data/password click here" (so lazy invitees don't get shocked when they see the form) ... Even better would be if the handling is adjustable via TS.
#3 Updated by Sebastian Fischer over 4 years ago

Comment Edit
I would disagree with this, because this way the invitee has no chance to accept the informations given.

If the inviter gives more information then name and email the invitee must at least has the change to confirm they are correct. So in this case he still needs to be forwarded to the form.
#4 Updated by Georg Schönweger over 4 years ago

Comment Edit
ok agree with you.
#5 Updated by Sebastian Fischer about 11 hours ago

Estimated time set to 10.00
Comment Edit
This feature needs a budget of 10 hours. Feel free to get in contact with me.

If this feature does not get funded in the next 12 month this feature gets rejected.

**Comment by garbast** [comment]
Solved in develop branch
