### ISSUE TITLE
PHP7 warning in RangeSelectViewHelper

### ISSUE THREAD

**Issue by AndreasA** [evoWeb/sf_register#30]
Due to the override of the default SelectViewHelper render method (with different parameters) there is an issue with the RangeSelectViewHelper.

In order to fix this I would add the additional attributes with registerArgument that way one can make the render method override simply be
function render() too.

However, in that case it would be possible to remove the render override completely and simply use in  $this->argument['step'] etc. in getOptions method.

**Comment by evoWeb** [comment]
If you are able i would like to ask you to hand a PR with the changes.

**Comment by AndreasA** [comment]
Can do. Not sure though when exactly. (Maybe this weekend but can't be sure).

**Comment by garbast** [comment]
The hole extensions was changed where PHP7 changes made it necessary. This is fixed.
