### ISSUE TITLE
PHP error FrontendUserGroup null given

### ISSUE THREAD

**Issue by AdvanceWM** [evoWeb/sf_register#32]
I get an error when testing user registration:
`#1: PHP Catchable Fatal Error: Argument 1 passed to TYPO3\CMS\Extbase\Domain\Model\FrontendUser::addUsergroup() must be an instance of TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup, null given, called in /home/sociald/dev/typo3conf/ext/sf_register/Classes/Controller/FeuserCreateController.php on line 364 and defined in /home/typo3_src-7.6.11/typo3/sysext/extbase/Classes/Domain/Model/FrontendUser.php line 204`
The FE User groups are defined. The Constants and Setup may be seen at [http://advancewebmarketing.com/d/RegisterConfiguration.txt](url)

We are trying to require FE User confirmation via email and Admin approval of FE Users using the configuration shown in Issue #22.

**Comment by evoWeb** [comment]
There is no error in the adding of usergroups. It has to be a configuration problem. Even with the provided typoscript i cant analyse what's causing the error. As it is an individual problem i only can offer you fee based support.
