### ISSUE TITLE
Wrong email to confirm registration?

### ISSUE THREAD

**Issue by Schweriner** [evoWeb/sf_register#39]
Hello,

I'm wondering about the mailconfigurations. When I configure confirmEmailPostCreate and notifyUserPostCreateSave  to "1" the user will be disabled and inside the correct group after saving the registration. But he gets the e-mail that his registration was successfull without an activation link?

This is caused by this logic inside the FeUserCreateController:

```
if ($this->isNotifyUser('PostCreateSave') && $this->settings['confirmEmailPostCreate']) {
            $user->setDisable(true);
            $user = $this->changeUsergroup($user, (int) $this->settings['usergroupPostSave']);
            $type = 'PostCreateConfirm';
        } elseif ($this->isNotifyAdmin('PostCreateSave') && $this->settings['acceptEmailPostCreate']) {
            $user->setDisable(true);
            $user = $this->changeUsergroup($user, (int) $this->settings['usergroupPostSave']);
            $type = 'PostCreateAccept';
        } else {
            // @todo check if removable
            //$user = $this->moveImageFile($user);
            $user = $this->changeUsergroup($user, (int) $this->settings['usergroup']);
            $type = 'PostCreateSave';
        }
```

This causes the mail "PostCreateConfirm" to be send. This is okay but the "PostCreateConfirm" should then contain the activation link instead of the "PostCreateSave" email?

**Comment by Schweriner** [comment]
This issue would be fixed with this Pull Request 
https://github.com/evoWeb/sf_register/pull/24

**Comment by garbast** [comment]
As described in the PR there are changes concerning the confirmation/refusal accaptance/denial of registration. Please check in development branch and reopen if more changes are needed. Please keep in mind that the labels will be revised in the next days as there were some changes too.
