### ISSUE TITLE
#1297759968: Exception while property mapping at property path "image.name": The identity property "IMG_3629.jpg" is no UID

### ISSUE THREAD

**Issue by emmemme** [evoWeb/sf_register#43]
I've a clean TYPO3 8.7.4 installation.
I've create the register page including the sf_register plugin
Filled the fields and choosed an image.
When I press the button Create, I retrive the following error:
**#1297759968: Exception while property mapping at property path "image.name": The identity property "IMG_3629.jpg" is no UID**

I found this issues [https://forum.typo3.org/index.php/t/215742/](https://forum.typo3.org/index.php/t/215742/) that says: 

> I managed to fix the issue. It was a dumb mistake in my Model:
> the image property was declared as "ObjectStorage" instead of "FileReference

Looking for this issues, I've found that field image in TYPO3\CMS\Extbase\Domain\Model\FrontendUser is declared as 
```
    /**
     * @var \TYPO3\CMS\Extbase\Persistence\ObjectStorage<\TYPO3\CMS\Extbase\Domain\Model\FileReference>
     */
    protected $image = null;
```

I made a brutal test changing the code in TYPO3\CMS\Extbase\Domain\Model\FrontendUser in this way:
```
    /**
     * image
     *
     * @var \TYPO3\CMS\Extbase\Domain\Model\FileReference
     */
    protected $image;

    /**
     * Returns the image
     *
     * @return \TYPO3\CMS\Extbase\Domain\Model\FileReference $image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Sets the image
     *
     * @param \TYPO3\CMS\Extbase\Domain\Model\FileReference $image
     * @return void
     */
    public function setImage(\TYPO3\CMS\Extbase\Domain\Model\FileReference $image)
    {
        $this->image = $image;
    }
```
and it's works. I can create the user and edit it.

I know that I could create my own image field and solve the problem without touching core functions.

But the question is: **did I miss something or the there is a problem with the image declaration in TYPO3\CMS\Extbase\Domain\Model\FrontendUser?**

**Comment by garbast** [comment]
Even though i did not test it right now your observation seems to be right. But, as you may already have seen the TYPO3\CMS\Extbase\Domain\Model\FrontendUser is not a class of the sf_register else it would have Evoweb as vendor. Since you cant override a method signature in php7.0 and higher this problem needs to be either fixed in the core by changing the method arguments or you need to add an own field. My preference would be a solution in the TYPO3\CMS\Extbase\Domain\Model\FrontendUser itself so please ask there.

**Comment by garbast** [comment]
This is fixed in the develop branch
