### ISSUE TITLE
Exception when trying to activate sf_register on TYPO3 8.7.6 LTS

### ISSUE THREAD

**Issue by DenisMir** [evoWeb/sf_register#45]
When trying to activate `sf_register` on TYPO3 8.7.6 LTS the following exception is thrown: 

```
Argument 2 passed to TYPO3\CMS\Core\Cache\CacheFactory::__construct() must be an instance of TYPO3\CMS\Core\Cache\CacheManager, none given
```
It is caused by line 48 in the `ext_tables.php` of `sf_register`:

```
        /**
         * TYPO3 cache factory
         *
         * @var \TYPO3\CMS\Core\Cache\CacheFactory $typo3CacheFactory
         */
        $typo3CacheFactory = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
            \TYPO3\CMS\Core\Cache\CacheFactory::class
        );
```
Please be aware that this class `CacheFactory` is gone in TYPO3 9:
https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/master/Breaking-80700-DeprecatedFunctionalityRemoved.html

**Comment by garbast** [comment]
This is fixed in the development branch. Please use this or wait till after the weekend. i need to prepare a release which this time is a bit more efford.
