### ISSUE TITLE
Which version is the one to use? (8.7.2 from TER vs. 8.7.3 from packagist vs. development)

### ISSUE THREAD

**Issue by DenisMir** [evoWeb/sf_register#46]
I have to ask this now since I'm lost with versions that don't work. 

Which is the most stable version with the most bugfixes at the moment? 

I'm coming from 8.7.2 in TER which throws an exception mentioned in #45. 

Then I have tried 8.7.3 from packagist loaded via composer. This version does have errors in the create workflow e.g. setting a type to "PostCreateConfirm" in the save action which doesn't make sense at all. 

Now I have looked in the development branch which changes the logic of the `saveAction` once again. But before trying it out I'd like to make sure that no other known bugs are waiting for me in the development branch.

**Comment by garbast** [comment]
Any known issue is present in the issue tracker or not known.

**Comment by DenisMir** [comment]
@garbast 
So the development tree is the one to use?

**Comment by garbast** [comment]
There will be a release coming up this week. i need to write down all the latest changes. and it will be an 8.8.0 which should reflect that there are major improvements but is still compatible for previous users.

**Comment by DenisMir** [comment]
Thank you very much. I will use the `develop` tree now and report back if I find further errors.
