### ISSUE TITLE
Adding new pages/folders etc. in page module doesn't work after activating sf_register 8.8.0 on TYPO3 8.7.6 LTS

### ISSUE THREAD

**Issue by DenisMir** [evoWeb/sf_register#47]
I'm working now with the `develop` branch of sf_register on TYPO3 8.7.6 LTS. When I enable the extension I'm not able to add new pages in the page module in the TYPO3 backend since I'm getting the following: 

![bildschirmfoto 2017-09-13 um 11 15 33](https://user-images.githubusercontent.com/157281/30369828-0b00118c-9876-11e7-9761-2a87acad0f71.png)

When I disable sf_register and reload the backend I'm getting the correct selection which looks like:

![bildschirmfoto 2017-09-13 um 11 24 39](https://user-images.githubusercontent.com/157281/30369864-27b1a67e-9876-11e7-8c23-bdedc279e007.png)

I'm not quite sure what triggers the error but it is affecting every 8LTS installation with sf_register enabled @ version 8.8.0.

**Comment by garbast** [comment]
Is fixed in develop since the latest push
