### ISSUE TITLE
cHash needs to be activated in email template links for TYPO3 8LTS

### ISSUE THREAD

**Issue by DenisMir** [evoWeb/sf_register#48]
It is necessary that the email template links (e.g. the confirm user) have the cHash activated. From 8LTS on it is required for extbase parameters. Without the cHash extbase parameters do not get evaluated. 

See: 
https://github.com/TYPO3/TYPO3.CMS/commit/2769e508741b8561f2236411bc81246a4d4d796d#diff-4b33df04c2fae7f06f8b1a0697200b19

At this point trying to confirm a user with the default email template just doesn't work and a 404 error page is shown.

**Comment by garbast** [comment]
This is fixed in the latest push in the develop branch. Please check if this helps your needs. If so please confirm and i will release a new tag.

**Comment by DenisMir** [comment]
It does work perfectly.

**Comment by garbast** [comment]
Will be tagged and released once #50 is fixed.
