### ISSUE TITLE
autologinPostConfirmation crashes with exception

### ISSUE THREAD

**Issue by DenisMir** [evoWeb/sf_register#50]
When activating the setting `autologinPostConfirmation` an exception gets thrown right here: 

https://github.com/evoWeb/sf_register/blob/develop/Classes/Controller/FeuserController.php#L642

The exception message: 
`Call to undefined method TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup::getFeloginRedirectPid()`

To be honest I don't understand the `autoLogin` in `FeuserController` method at all since it searches for a redirectPid which it never uses.

**Comment by garbast** [comment]
It would make sense if the error was raised in the line earlier with the if condition. Please send in a screenshot of the error message.

But it's true the redirecting part self is missing.

**Comment by DenisMir** [comment]
@garbast Indeed it is in the line above with the if condition.
