### ISSUE TITLE
What is better to choose for TYPO3 frontend user registration and management?

### ISSUE THREAD

**Issue by typo3ua** [evoWeb/sf_register#55]
Hello!
I have:
- ext: sf_register
- ext: sr_feuser_register
- ext: femanager

But I stand is before choice... What is better to choose for TYPO3 frontend user registration and management?
**If is the ext: sf_register so why? What are its benefits?**

**Comment by garbast** [comment]
To answer your question consult the documentation. I'm not going to pitch my extension for you. If you want to use it welcome. If you don't like it i don't care. I offer what i think should be in.
