### ISSUE TITLE
Sorting of Field via Typoscript at Frotend

### ISSUE THREAD

**Issue by enilee** [evoWeb/sf_register#56]
Hello,

i use TYPO3 8.7 and the sf_register 8.8.1

I try in typoscript to bring the fields in a sequence. Unfortunately, this does not work because a field is always output after the last field, although it is arranged differently in the typoscipt.

My example TS:

plugin.tx_sfregister {
    settings {
        fields {
            createDefaultSelected {
                10 = gender
                20 = title
                30 = clear
                40 = firstName
                50 = lastName
                55 = clear
                60 = username
                70 = company
                80 = telephone
                90 = mobilephone
                100 = clear
                110 = email
                120 = emailRepeat
                130 = clear
                140 = address
                150 = zip
                160 = city
                170 = clear
                **180 = dateOfBirth**
                190 = clear
                200 = password
                210 = passwordRepeat
                220 = clear
                230 = privacy
                240 = gtc
                250 = change
                260 = submit_captcha
                270 >
                280 >
                290 >
                300 >
                310 >
                320 >
                330 >
                340 >
                350 >
                360 >
                370 >
                380 >
                390 >
                400 >
            }
        }
    }
}

The Output:
dateOfBirth is not under the address inputs

![image](https://user-images.githubusercontent.com/17785409/38253095-0e5a18b2-3756-11e8-84b2-8f68e3cd2b0f.png)

Unfortunately, I found no solution.

**Comment by garbast** [comment]
dateOfBirth i non of the preconfigured fields. Please have a look at the end of in /Configuration/TypoScript/Fields/setup.typoscript
There you see that you need to define what partials are configured already and you need to add a definition in your TypoScript.
