### ISSUE TITLE
It's not work under typo3- v9.3, can you renew it?

### ISSUE THREAD

**Issue by jooler** [evoWeb/sf_register#64]
all register extension can not work in typo3-v9 
can you make it work?
thank you.

**Comment by jooler** [comment]
Core: Error handler (FE): PHP Warning: Declaration of Evoweb\SfRegister\ViewHelpers\Form\RequiredViewHelper::render($fieldName) should be compatible with TYPO3Fluid\Fluid\Core\ViewHelper\AbstractTagBasedViewHelper::render() in /Users/jerr/WebServer/typo3.v9/typo3conf/ext/sf_register/Classes/ViewHelpers/Form/RequiredViewHelper.php line 107

**Comment by garbast** [comment]
This is already fixed in the develop branch. https://github.com/evoWeb/sf_register/blob/dabbf54c97ad9fa202d330957ec3337d95536a1a/Classes/ViewHelpers/Form/RequiredViewHelper.php#L72
