### ISSUE TITLE
Invalid realURL configuration if 'encodeSpURL_postProc' or 'decodeSpURL_preProc' is used

### ISSUE THREAD

**Issue by SC-cmarquardt** [evoWeb/sf_register#65]
Hi,

your realURL configuration leads to an error (trim expects parameter 1 to be string, array given) if the realURL Hooks 'encodeSpURL_postProc' or 'decodeSpURL_preProc' are used.

Array position is 
`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['encodeSpURL_postProc']` (see https://github.com/dmitryd/typo3-realurl/blob/development/Classes/Encoder/UrlEncoder.php#L282)
which is at the same level as the domain configuration e.g.
`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['realurl']['_DEFAULT']`.

So when https://github.com/evoWeb/sf_register/blob/develop/Configuration/Realurl/configuration.php#L49 runs, a complex array structure is now located at a position where only a simple array of strings should be.

Proposed solution is to check for the key `postVarSets` because this one only exists in the context of domain configuration and not hook configuration. 

See PR: https://github.com/evoWeb/sf_register/pull/66

Kind regards,
Christopher

**Comment by garbast** [comment]
PR merged

**Comment by IndyIndyIndy** [comment]
Hi, is a backport to 8.8.x planned for this fix? This bug makes the ext pretty much unusable in TYPO3 8.7 and the latter versions for TYPO3 9.5 don't require this fix as realurl isn't supported in these versions anymore. :(

**Comment by garbast** [comment]
There will be no backports for 8.x anymore. The develop branch does not have this configuration anymore.

Set the setRealurlConfigByDefault to disable in extension manager and the extension is usable without problem.
