### ISSUE TITLE
realurl not working

### ISSUE THREAD

**Issue by electricretina** [evoWeb/sf_register#8]
I am running TYPO3 7.6 with reaurl and the latest master branch of sf_register. When I submit the user create form realurl says: 

Reason: Segment "create" was not a keyword for a postVarSet as expected on page with id=3.

create is the page name where the plugin is located and id=3 is the page with the user records. 

realurl is running with auto config. 

I have manually added the sf_register realurl config to the auto create realurl config file but it isn't working. 

Is this an issue with sf_register or realurl?

**Comment by garbast** [comment]
As sf_register only kicks in after realurl has converted the speaking url into $_GET parameter it has nothing to do with sf_register but with your settings for realurl. Sorry but i can't help you with that.
