### ISSUE TITLE
problems with SrFreecapAdapter::render

### ISSUE THREAD

**Issue by netzcoop** [evoWeb/sf_register#82]
hello sf_register team

i have a problem (commit 86cbfa4de96c4519a89d1a698d2c85d4ddf7c578 ) with the return of the SrFreecapAdapter::render function. 

    public function render(): string
    {
        /* .... */
       $output = array_combine($this->keys, $values);
        /* .... */
        return $output;
    }

the declaration of the return is a string, but the function gives always an array back, analog the other captcha adapter

kind regards

**Comment by garbast** [comment]
Feel free to hand in a PR.

**Comment by garbast** [comment]
I needed to change the signature to string|array because in error case or other adapters string is returned
