### ISSUE TITLE
Bargraph doesn't work

### ISSUE THREAD

**Issue by moskos88** [evoWeb/sf_register#84]
Dear sf_register Team,
after last update to version 9.0.0 the so-called bargraph stopped working. By typing something in the password field, there is a js exception shown in console:
![bildschirmfoto 2019-02-01 um 12 54 13](https://user-images.githubusercontent.com/22467885/52121692-ce180380-2620-11e9-9ed8-d99eddf10dc5.png)

To be more clear: doesn't work means, that typing any chars in the password field, there is no action on the 'bargraph' and user is not informed, how strong is the currently typed password.

**Comment by garbast** [comment]
It's a problem with the build process. I will have a look into it at the weekend.

**Comment by garbast** [comment]
What browser do you use? I've tested in latest Chrome, Firefox and via BrowserStack even IE11

**Comment by garbast** [comment]
In addition make sure, that you load the default templates as i changed them away from <iframe> towards <meter>

**Comment by moskos88** [comment]
OMG. Yes you are right. I've missed it in the code, we are using own templates and the iframe was just there. I replaced it with meter tag and now it works. Thx!
