### ISSUE TITLE
Bargraph scroll on chrome

### ISSUE THREAD

**Issue by moskos88** [evoWeb/sf_register#85]
In the chrome browser, the so-called bargraph is shown a little bit hidden between fields and with a scroll, even after the commit 77052515cd7b389232830a2f65b8daefd78cc7d1 adding tag "scrolling"=no.

![bildschirmfoto 2019-02-01 um 13 03 53](https://user-images.githubusercontent.com/22467885/52122009-dfaddb00-2621-11e9-9d65-5188e86e3c69.png)

**Comment by garbast** [comment]
Feel free to push an PR.

It was tested in latest chrome. With the ".tx_evoweb_sfregister #bargraph" css loaded it should work. The css defines a height of 14px and the svg has width="372px" height="14px" given.

Maybe the browser interprets the viewBox="0 0 138 7" wrong. Please try changing that in the svg and reply with the result.

**Comment by moskos88** [comment]
So I made some little research on this topic, as I am not a frontend guy, I also spoke about this issue with one frontend developer in our house. The proposition of solving this issue is from my side to change the px value of SVG height to be a per cent value (100%). I tested in on Chrome, Firefox and Safari. It works.

PR: https://github.com/evoWeb/sf_register/pull/86

**Comment by garbast** [comment]
Fixed with merged pull request

**Comment by garbast** [comment]
In addition i replaced the bargraph iframe with a HTML5 meter tag
