### ISSUE TITLE
testPassword is not working

### ISSUE THREAD

**Issue by waue** [evoWeb/sf_register#87]
sf_register/Resources/Public/JavaScript/sf_register.js

Uncaught TypeError: window.testPassword is not a function at HTMLInputElement.module.callTestPassword (sf_register.js:67)

**Comment by garbast** [comment]
Please check your template and remove any window.testPassword occurancies. The method call is attached in sf_register.js to input#sfrpassword on keyup

**Comment by waue** [comment]
no, I don t think so - it seems to be in the wron scope 
if I put the function testPassword in the global scope everything works fine

**Comment by garbast** [comment]
Cant confirm the problem. What version of the extension are you using? What core? What browser?

**Comment by waue** [comment]
I used version 9.0.0 of your extension and TYPO3 version 9.5.4 all with composer
I just tried your develop version and it works :)

**Comment by garbast** [comment]
In version 9.1.0 the changes were already release. So updating to it should work.

**Comment by garbast** [comment]
Sorry this release is still pending. Will be out today.

**Comment by garbast** [comment]
Tag 9.1.0 is created and should also appear in TER soon
