### ISSUE TITLE
[FEATURE] Add password reset form

### ISSUE THREAD

**Issue by BenjaminBeck** [evoWeb/sf_register#9]
I haven't looked into the code yet but from the documentation and previous usage i believe this functionality is missing.

**Comment by BenjaminBeck** [comment]
Ok, just saw that "change password" is already listed in "whats already in there".

**Comment by evoWeb** [comment]
There is only a password change form because the felogin provides the password reset on its own. We do not intent to doublicate functionality already provided by the core.
