### ISSUE TITLE
Fix fetching validation settings in required viewhelper

### ISSUE THREAD

**Issue by AstCommodore** [evoWeb/sf_register#91]
Hello @garbast 

in version 9.3 you fixed the required viewhelper and changed the str_replace, see
[https://github.com/evoWeb/sf_register/commit/32458890c71d6dffcb5a128e626d4d78ad782d57#diff-9a2667240a53c354deac5285b6b92d36](url)

But in my new TYPO3 9.5.11 / sfregister 9.3 installation I get the 'feusercreate' as $mode, so the required fields are not marked in Frontend.

It seems, that you didn't changed the TypoScript under https://github.com/evoWeb/sf_register/blob/develop/Configuration/TypoScript/Common/setup.typoscript.

Is there an unseen breaking change for me or is you view helper fix not finished at all?

Greetings!

**Comment by garbast** [comment]
I think it has to do with the change for TYPO3 10.x https://github.com/evoWeb/sf_register/blob/e82f678e00006fb23d91b5cf24ef9714d5899ca2/ext_localconf.php#L26
So yes there is a change that can and should be fixed. Sometimes it's bad trying to stay compatible for multiple major versions...

**Comment by garbast** [comment]
Fixed in commit e362ec0
