### ISSUE TITLE
Links at emails contain doubled ampersand &amp;  

### ISSUE THREAD

**Issue by jkujku** [evoWeb/sf_register#98]
Typo3 9.5.11 
sf_register 9.4.0

The links at emails are broken because of a quoted and an unquoted ampersand.

**Example:** 

`https://example.com/register/?tx_sfregister_form%5Baction%5D=confirm&amp;tx_sfregister_form%5Bcontroller%5D=FeuserCreate&amp;tx_sfregister_form%5Bhash%5D=ab6ca257615e6baa3d6065b47b15f3f4eb7753cf&amp;tx_sfregister_form%5Buser%5D=25&amp;cHash=76535a1265dc84f9ac40c947e3bc44c0"`

**Maybe a solution:**

Maybe this is caused by changed behaviour of ViewHelpers used in StandAloneViews and a solution would be not to use \Link\ActionViewhelper but Uri\ActionViewHelper? See this SO post: https://stackoverflow.com/questions/52060881/typo3-fluid-furi-action-encodes-with-amp/52061042

Testwise I used f:link.action and f:link.uri in the registration email template, where the first gives an incorrect url and the second looks good.

At UserNotificationPostCreateSave.html

```
	<f:link.action arguments="{user: user.uid}" action="confirm" controller="FeuserCreate" absolute="true"></f:link.action>

	<f:format.raw><f:uri.action arguments="{user: user.uid}" action="confirm" controller="FeuserCreate" absolute="true"></f:uri.action></f:format.raw>
```

At resulting email

```
	<a href="https://example.com/register/?tx_sfregister_form%5Baction%5D=confirm&amp;tx_sfregister_form%5Bcontroller%5D=FeuserCreate&amp;tx_sfregister_form%5Buser%5D=26&amp;cHash=d994be0f471c79a22187ef3da6e9675d"></a>

	https://example.com/register/?tx_sfregister_form%5Baction%5D=confirm&tx_sfregister_form%5Bcontroller%5D=FeuserCreate&tx_sfregister_form%5Buser%5D=26&cHash=d994be0f471c79a22187ef3da6e9675d
```

Greeting, j.

**Comment by garbast** [comment]
&amp; are fine in links and browser understand the. Explanation can be found here https://text-symbols.com/html/encode/
